#!/usr/bin/env python3
"""
Загрузка игровых зон в базу.

Запускается сколько угодно раз: зоны сопоставляются по имени, существующие
обновляются, новые добавляются. Ничего не удаляет.

Зона описывается центром и радиусом, а не готовым полигоном: так список
читается и правится, а квадрат вокруг центра для выбора случайной точки ничем
не хуже нарисованного вручную контура.

    python scripts/seed.py
    python scripts/seed.py --only-new
"""

import argparse
import asyncio
import json
import logging
import math
import sys
from dataclasses import dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from geoalchemy2 import WKTElement
from sqlalchemy import select

from app.database import AsyncSessionLocal
from app.models.location_zone import LocationZone

logger = logging.getLogger("seed")

# Один градус широты — примерно столько километров
KM_PER_DEGREE = 111.19


@dataclass(frozen=True)
class ZoneSpec:
    """Описание зоны в списке ниже."""

    name: str
    description: str
    difficulty: int
    category: str
    country: str
    region: str
    continent: str
    tags: list[str]
    longitude: float
    latitude: float
    radius_km: float

    def polygon_wkt(self) -> str:
        """
        Квадрат вокруг центра.

        По долготе градус короче тем сильнее, чем ближе к полюсу, поэтому
        полуширина делится на косинус широты.
        """
        half_lat = self.radius_km / KM_PER_DEGREE
        cos_lat = max(abs(math.cos(math.radians(self.latitude))), 0.05)
        half_lon = half_lat / cos_lat

        west, east = self.longitude - half_lon, self.longitude + half_lon
        south, north = self.latitude - half_lat, self.latitude + half_lat

        corners = [(west, south), (west, north), (east, north), (east, south), (west, south)]
        points = ", ".join(f"{lon} {lat}" for lon, lat in corners)

        return f"POLYGON(({points}))"


ZONES: list[ZoneSpec] = [
    ZoneSpec(
        name="Москва, центр",
        description="Радиально-кольцевая планировка и излучина реки",
        difficulty=1,
        category="city",
        country="Россия",
        region="Москва",
        continent="europe",
        tags=["столица", "кольца"],
        longitude=37.62,
        latitude=55.75,
        radius_km=18,
    ),
    ZoneSpec(
        name="Санкт-Петербург",
        description="Каналы, Нева и прямоугольные кварталы",
        difficulty=1,
        category="city",
        country="Россия",
        region="Санкт-Петербург",
        continent="europe",
        tags=["каналы", "Нева"],
        longitude=30.32,
        latitude=59.94,
        radius_km=15,
    ),
    ZoneSpec(
        name="Париж",
        description="Плотная застройка, Сена и лучи проспектов",
        difficulty=1,
        category="city",
        country="Франция",
        region="Иль-де-Франс",
        continent="europe",
        tags=["столица", "Сена"],
        longitude=2.35,
        latitude=48.86,
        radius_km=10,
    ),
    ZoneSpec(
        name="Лондон",
        description="Темза и парки среди сплошной застройки",
        difficulty=1,
        category="city",
        country="Великобритания",
        region="Большой Лондон",
        continent="europe",
        tags=["столица", "Темза"],
        longitude=-0.13,
        latitude=51.51,
        radius_km=14,
    ),
    ZoneSpec(
        name="Берлин",
        description="Шпрее, Тиргартен и широкие магистрали",
        difficulty=1,
        category="city",
        country="Германия",
        region="Берлин",
        continent="europe",
        tags=["столица", "Шпрее"],
        longitude=13.4,
        latitude=52.52,
        radius_km=13,
    ),
    ZoneSpec(
        name="Рим",
        description="Тибр, античные площади и хаотичные кварталы",
        difficulty=2,
        category="historical",
        country="Италия",
        region="Лацио",
        continent="europe",
        tags=["античность", "Тибр"],
        longitude=12.5,
        latitude=41.9,
        radius_km=10,
    ),
    ZoneSpec(
        name="Барселона",
        description="Квадратная сетка Эшампле у самого моря",
        difficulty=1,
        category="city",
        country="Испания",
        region="Каталония",
        continent="europe",
        tags=["сетка", "море"],
        longitude=2.17,
        latitude=41.39,
        radius_km=8,
    ),
    ZoneSpec(
        name="Амстердам",
        description="Полукольца каналов и узкие кварталы",
        difficulty=1,
        category="city",
        country="Нидерланды",
        region="Северная Голландия",
        continent="europe",
        tags=["каналы"],
        longitude=4.9,
        latitude=52.37,
        radius_km=7,
    ),
    ZoneSpec(
        name="Венеция",
        description="Острова лагуны, прорезанные каналами",
        difficulty=1,
        category="coast",
        country="Италия",
        region="Венето",
        continent="europe",
        tags=["лагуна", "острова"],
        longitude=12.33,
        latitude=45.44,
        radius_km=5,
    ),
    ZoneSpec(
        name="Стокгольм",
        description="Город на островах между озером и морем",
        difficulty=2,
        category="coast",
        country="Швеция",
        region="Стокгольм",
        continent="europe",
        tags=["острова", "шхеры"],
        longitude=18.07,
        latitude=59.33,
        radius_km=12,
    ),
    ZoneSpec(
        name="Прага",
        description="Влтава и плотный исторический центр",
        difficulty=2,
        category="historical",
        country="Чехия",
        region="Прага",
        continent="europe",
        tags=["Влтава"],
        longitude=14.42,
        latitude=50.09,
        radius_km=8,
    ),
    ZoneSpec(
        name="Вена",
        description="Дунай и кольцо бульваров",
        difficulty=2,
        category="city",
        country="Австрия",
        region="Вена",
        continent="europe",
        tags=["Дунай", "кольцо"],
        longitude=16.37,
        latitude=48.21,
        radius_km=10,
    ),
    ZoneSpec(
        name="Афины",
        description="Плотная застройка между холмами и морем",
        difficulty=2,
        category="historical",
        country="Греция",
        region="Аттика",
        continent="europe",
        tags=["античность"],
        longitude=23.73,
        latitude=37.98,
        radius_km=10,
    ),
    ZoneSpec(
        name="Швейцарские Альпы",
        description="Ледники, узкие долины и серпантины",
        difficulty=4,
        category="mountains",
        country="Швейцария",
        region="Вале",
        continent="europe",
        tags=["горы", "ледники"],
        longitude=7.85,
        latitude=46.1,
        radius_km=45,
    ),
    ZoneSpec(
        name="Норвежские фьорды",
        description="Узкие заливы между отвесными склонами",
        difficulty=4,
        category="coast",
        country="Норвегия",
        region="Вестланд",
        continent="europe",
        tags=["фьорды"],
        longitude=6.5,
        latitude=61.2,
        radius_km=55,
    ),
    ZoneSpec(
        name="Исландия, юг",
        description="Чёрные пески, ледники и лавовые поля",
        difficulty=5,
        category="nature",
        country="Исландия",
        region="Сюдюрланд",
        continent="europe",
        tags=["вулканы", "ледники"],
        longitude=-19.0,
        latitude=63.7,
        radius_km=60,
    ),
    ZoneSpec(
        name="Тоскана",
        description="Холмы, виноградники и вытянутые фермы",
        difficulty=3,
        category="rural",
        country="Италия",
        region="Тоскана",
        continent="europe",
        tags=["холмы", "поля"],
        longitude=11.3,
        latitude=43.4,
        radius_km=40,
    ),
    ZoneSpec(
        name="Нидерланды, польдеры",
        description="Идеально прямые каналы и прямоугольные поля",
        difficulty=3,
        category="rural",
        country="Нидерланды",
        region="Флеволанд",
        continent="europe",
        tags=["польдеры", "каналы"],
        longitude=5.6,
        latitude=52.5,
        radius_km=35,
    ),
    ZoneSpec(
        name="Рурский бассейн",
        description="Заводы, отвалы и плотная сеть дорог",
        difficulty=4,
        category="industrial",
        country="Германия",
        region="Северный Рейн — Вестфалия",
        continent="europe",
        tags=["заводы"],
        longitude=7.1,
        latitude=51.5,
        radius_km=30,
    ),
    ZoneSpec(
        name="Шотландское высокогорье",
        description="Голые склоны, озёра и почти нет дорог",
        difficulty=4,
        category="mountains",
        country="Великобритания",
        region="Хайленд",
        continent="europe",
        tags=["озёра", "вереск"],
        longitude=-4.8,
        latitude=57.2,
        radius_km=55,
    ),
    ZoneSpec(
        name="Дунайская дельта",
        description="Лабиринт проток и тростника",
        difficulty=5,
        category="nature",
        country="Румыния",
        region="Тулча",
        continent="europe",
        tags=["дельта", "плавни"],
        longitude=29.2,
        latitude=45.1,
        radius_km=40,
    ),
    ZoneSpec(
        name="Крымское побережье",
        description="Горы, спускающиеся к морю",
        difficulty=3,
        category="coast",
        country="Россия",
        region="Крым",
        continent="europe",
        tags=["море", "горы"],
        longitude=34.2,
        latitude=44.55,
        radius_km=30,
    ),
    ZoneSpec(
        name="Карелия, озёра",
        description="Тысячи озёр среди тайги",
        difficulty=4,
        category="nature",
        country="Россия",
        region="Карелия",
        continent="europe",
        tags=["озёра", "тайга"],
        longitude=32.5,
        latitude=62.5,
        radius_km=70,
    ),
    ZoneSpec(
        name="Сочи, побережье",
        description="Полоса города между морем и хребтом",
        difficulty=2,
        category="coast",
        country="Россия",
        region="Краснодарский край",
        continent="europe",
        tags=["море", "горы"],
        longitude=39.75,
        latitude=43.58,
        radius_km=18,
    ),
    ZoneSpec(
        name="Казань",
        description="Кремль, слияние рек и новые кварталы",
        difficulty=2,
        category="city",
        country="Россия",
        region="Татарстан",
        continent="europe",
        tags=["реки"],
        longitude=49.11,
        latitude=55.79,
        radius_km=14,
    ),
    ZoneSpec(
        name="Токио",
        description="Бесконечная застройка вокруг залива",
        difficulty=2,
        category="city",
        country="Япония",
        region="Канто",
        continent="asia",
        tags=["столица", "залив"],
        longitude=139.7,
        latitude=35.69,
        radius_km=20,
    ),
    ZoneSpec(
        name="Киото",
        description="Прямоугольная сетка в кольце гор",
        difficulty=2,
        category="historical",
        country="Япония",
        region="Кансай",
        continent="asia",
        tags=["сетка", "храмы"],
        longitude=135.77,
        latitude=35.01,
        radius_km=10,
    ),
    ZoneSpec(
        name="Пекин",
        description="Концентрические кольца вокруг запретного города",
        difficulty=2,
        category="city",
        country="Китай",
        region="Пекин",
        continent="asia",
        tags=["кольца"],
        longitude=116.4,
        latitude=39.9,
        radius_km=20,
    ),
    ZoneSpec(
        name="Шанхай",
        description="Небоскрёбы и петля Хуанпу",
        difficulty=2,
        category="city",
        country="Китай",
        region="Шанхай",
        continent="asia",
        tags=["река", "высотки"],
        longitude=121.47,
        latitude=31.23,
        radius_km=18,
    ),
    ZoneSpec(
        name="Гонконг",
        description="Высотки, зажатые между сопками и морем",
        difficulty=2,
        category="city",
        country="Китай",
        region="Гонконг",
        continent="asia",
        tags=["высотки", "море"],
        longitude=114.17,
        latitude=22.32,
        radius_km=10,
    ),
    ZoneSpec(
        name="Сингапур",
        description="Остров-город с намывными берегами",
        difficulty=2,
        category="city",
        country="Сингапур",
        region="Сингапур",
        continent="asia",
        tags=["остров", "порт"],
        longitude=103.82,
        latitude=1.35,
        radius_km=12,
    ),
    ZoneSpec(
        name="Дубай",
        description="Пальмовые острова и прямые магистрали в пустыне",
        difficulty=1,
        category="architecture",
        country="ОАЭ",
        region="Дубай",
        continent="asia",
        tags=["намыв", "пустыня"],
        longitude=55.27,
        latitude=25.2,
        radius_km=18,
    ),
    ZoneSpec(
        name="Стамбул",
        description="Пролив, разрезающий город надвое",
        difficulty=1,
        category="city",
        country="Турция",
        region="Мармара",
        continent="asia",
        tags=["Босфор"],
        longitude=28.98,
        latitude=41.01,
        radius_km=18,
    ),
    ZoneSpec(
        name="Иерусалим",
        description="Плотный старый город на холмах",
        difficulty=3,
        category="historical",
        country="Израиль",
        region="Иерусалим",
        continent="asia",
        tags=["холмы"],
        longitude=35.22,
        latitude=31.78,
        radius_km=8,
    ),
    ZoneSpec(
        name="Гималаи, Кхумбу",
        description="Снежные хребты и ледники",
        difficulty=5,
        category="mountains",
        country="Непал",
        region="Кхумбу",
        continent="asia",
        tags=["горы", "снег"],
        longitude=86.9,
        latitude=27.9,
        radius_km=45,
    ),
    ZoneSpec(
        name="Пустыня Гоби",
        description="Голая степь, переходящая в пески",
        difficulty=5,
        category="desert",
        country="Монголия",
        region="Гоби",
        continent="asia",
        tags=["пустыня", "степь"],
        longitude=103.0,
        latitude=43.0,
        radius_km=200,
    ),
    ZoneSpec(
        name="Озеро Байкал",
        description="Вытянутая котловина среди тайги",
        difficulty=4,
        category="nature",
        country="Россия",
        region="Прибайкалье",
        continent="asia",
        tags=["озеро", "тайга"],
        longitude=107.5,
        latitude=53.5,
        radius_km=150,
    ),
    ZoneSpec(
        name="Камчатка, вулканы",
        description="Конусы вулканов и пепловые поля",
        difficulty=5,
        category="mountains",
        country="Россия",
        region="Камчатка",
        continent="asia",
        tags=["вулканы"],
        longitude=159.5,
        latitude=54.5,
        radius_km=70,
    ),
    ZoneSpec(
        name="Алтай",
        description="Хребты, реки и высокогорные плато",
        difficulty=4,
        category="mountains",
        country="Россия",
        region="Алтай",
        continent="asia",
        tags=["горы", "реки"],
        longitude=87.0,
        latitude=50.0,
        radius_km=90,
    ),
    ZoneSpec(
        name="Рисовые террасы Ифугао",
        description="Ступени полей по склонам",
        difficulty=4,
        category="rural",
        country="Филиппины",
        region="Лусон",
        continent="asia",
        tags=["террасы", "рис"],
        longitude=121.1,
        latitude=16.93,
        radius_km=25,
    ),
    ZoneSpec(
        name="Мальдивы",
        description="Кольца атоллов в открытом океане",
        difficulty=4,
        category="islands",
        country="Мальдивы",
        region="Индийский океан",
        continent="asia",
        tags=["атоллы", "лагуны"],
        longitude=73.2,
        latitude=3.5,
        radius_km=60,
    ),
    ZoneSpec(
        name="Дельта Меконга",
        description="Сеть проток и рисовых полей",
        difficulty=4,
        category="rural",
        country="Вьетнам",
        region="Меконг",
        continent="asia",
        tags=["протоки", "рис"],
        longitude=105.8,
        latitude=10.2,
        radius_km=60,
    ),
    ZoneSpec(
        name="Аральское море",
        description="Высохшее дно и остатки воды",
        difficulty=5,
        category="desert",
        country="Узбекистан",
        region="Каракалпакстан",
        continent="asia",
        tags=["высохшее море"],
        longitude=59.5,
        latitude=45.0,
        radius_km=90,
    ),
    ZoneSpec(
        name="Тибетское плато",
        description="Голые высокогорные равнины и озёра",
        difficulty=5,
        category="mountains",
        country="Китай",
        region="Тибет",
        continent="asia",
        tags=["плато", "озёра"],
        longitude=89.0,
        latitude=32.0,
        radius_km=150,
    ),
    ZoneSpec(
        name="Дели",
        description="Плотная застройка и радиальные проспекты",
        difficulty=2,
        category="city",
        country="Индия",
        region="Дели",
        continent="asia",
        tags=["столица"],
        longitude=77.21,
        latitude=28.61,
        radius_km=20,
    ),
    ZoneSpec(
        name="Мумбаи",
        description="Полуостров, застроенный целиком",
        difficulty=2,
        category="city",
        country="Индия",
        region="Махараштра",
        continent="asia",
        tags=["полуостров"],
        longitude=72.85,
        latitude=19.08,
        radius_km=15,
    ),
    ZoneSpec(
        name="Сеул",
        description="Река Ханган между горными кварталами",
        difficulty=2,
        category="city",
        country="Южная Корея",
        region="Сеул",
        continent="asia",
        tags=["река", "горы"],
        longitude=126.98,
        latitude=37.57,
        radius_km=16,
    ),
    ZoneSpec(
        name="Бангкок",
        description="Изгибы Чаопхрайи среди сплошной застройки",
        difficulty=2,
        category="city",
        country="Таиланд",
        region="Бангкок",
        continent="asia",
        tags=["река"],
        longitude=100.5,
        latitude=13.75,
        radius_km=16,
    ),
    ZoneSpec(
        name="Долина Царей",
        description="Скалы и русла посреди пустыни у Нила",
        difficulty=3,
        category="historical",
        country="Египет",
        region="Луксор",
        continent="asia",
        tags=["археология", "Нил"],
        longitude=32.6,
        latitude=25.74,
        radius_km=12,
    ),
    ZoneSpec(
        name="Каспийское побережье",
        description="Полупустыня, упирающаяся в море",
        difficulty=4,
        category="coast",
        country="Казахстан",
        region="Мангистау",
        continent="asia",
        tags=["полупустыня"],
        longitude=51.2,
        latitude=43.6,
        radius_km=60,
    ),
    ZoneSpec(
        name="Сахара, эрг Убари",
        description="Дюны и редкие озёра между ними",
        difficulty=5,
        category="desert",
        country="Ливия",
        region="Феццан",
        continent="africa",
        tags=["дюны"],
        longitude=12.8,
        latitude=26.6,
        radius_km=90,
    ),
    ZoneSpec(
        name="Каир",
        description="Плотный город на обоих берегах Нила",
        difficulty=2,
        category="city",
        country="Египет",
        region="Каир",
        continent="africa",
        tags=["Нил", "столица"],
        longitude=31.24,
        latitude=30.05,
        radius_km=18,
    ),
    ZoneSpec(
        name="Пирамиды Гизы",
        description="Правильные треугольники на краю песков",
        difficulty=1,
        category="historical",
        country="Египет",
        region="Гиза",
        continent="africa",
        tags=["пирамиды"],
        longitude=31.13,
        latitude=29.98,
        radius_km=6,
    ),
    ZoneSpec(
        name="Кейптаун",
        description="Город между столовой горой и двумя океанами",
        difficulty=2,
        category="coast",
        country="ЮАР",
        region="Западный Кейп",
        continent="africa",
        tags=["гора", "океан"],
        longitude=18.42,
        latitude=-33.92,
        radius_km=15,
    ),
    ZoneSpec(
        name="Дельта Окаванго",
        description="Веер проток, растворяющийся в песке",
        difficulty=5,
        category="nature",
        country="Ботсвана",
        region="Северо-Запад",
        continent="africa",
        tags=["дельта", "саванна"],
        longitude=22.9,
        latitude=-19.3,
        radius_km=70,
    ),
    ZoneSpec(
        name="Килиманджаро",
        description="Одинокий конус над саванной",
        difficulty=4,
        category="mountains",
        country="Танзания",
        region="Килиманджаро",
        continent="africa",
        tags=["вулкан"],
        longitude=37.35,
        latitude=-3.07,
        radius_km=25,
    ),
    ZoneSpec(
        name="Марракеш",
        description="Глиняный старый город у подножия Атласа",
        difficulty=3,
        category="city",
        country="Марокко",
        region="Марракеш",
        continent="africa",
        tags=["медина"],
        longitude=-7.99,
        latitude=31.63,
        radius_km=10,
    ),
    ZoneSpec(
        name="Виктория, водопад",
        description="Разлом, куда обрушивается река",
        difficulty=3,
        category="nature",
        country="Замбия",
        region="Ливингстон",
        continent="africa",
        tags=["водопад"],
        longitude=25.86,
        latitude=-17.92,
        radius_km=12,
    ),
    ZoneSpec(
        name="Сахель",
        description="Пересыхающие русла и редкие поля",
        difficulty=5,
        category="rural",
        country="Мали",
        region="Мопти",
        continent="africa",
        tags=["сушь", "русла"],
        longitude=-4.2,
        latitude=14.5,
        radius_km=80,
    ),
    ZoneSpec(
        name="Мадагаскар, запад",
        description="Красная земля, изрезанная эрозией",
        difficulty=5,
        category="nature",
        country="Мадагаскар",
        region="Мелаки",
        continent="africa",
        tags=["эрозия"],
        longitude=44.5,
        latitude=-19.0,
        radius_km=70,
    ),
    ZoneSpec(
        name="Дельта Нила",
        description="Веер проток и сплошные поля",
        difficulty=3,
        category="rural",
        country="Египет",
        region="Дельта",
        continent="africa",
        tags=["дельта", "поля"],
        longitude=31.2,
        latitude=30.9,
        radius_km=55,
    ),
    ZoneSpec(
        name="Найроби",
        description="Город на краю национального парка",
        difficulty=3,
        category="city",
        country="Кения",
        region="Найроби",
        continent="africa",
        tags=["саванна"],
        longitude=36.82,
        latitude=-1.29,
        radius_km=14,
    ),
    ZoneSpec(
        name="Серенгети",
        description="Плоская саванна с редкими деревьями",
        difficulty=5,
        category="nature",
        country="Танзания",
        region="Серенгети",
        continent="africa",
        tags=["саванна"],
        longitude=34.8,
        latitude=-2.3,
        radius_km=70,
    ),
    ZoneSpec(
        name="Намиб, Соссусфлей",
        description="Огромные дюны и белые солончаки",
        difficulty=5,
        category="desert",
        country="Намибия",
        region="Хардап",
        continent="africa",
        tags=["дюны", "солончак"],
        longitude=15.4,
        latitude=-24.7,
        radius_km=40,
    ),
    ZoneSpec(
        name="Нью-Йорк, Манхэттен",
        description="Прямоугольная сетка и зелёный прямоугольник парка",
        difficulty=1,
        category="city",
        country="США",
        region="Нью-Йорк",
        continent="north_america",
        tags=["сетка", "парк"],
        longitude=-73.97,
        latitude=40.78,
        radius_km=10,
    ),
    ZoneSpec(
        name="Сан-Франциско",
        description="Сетка улиц на холмах у залива",
        difficulty=1,
        category="city",
        country="США",
        region="Калифорния",
        continent="north_america",
        tags=["холмы", "залив"],
        longitude=-122.44,
        latitude=37.76,
        radius_km=10,
    ),
    ZoneSpec(
        name="Лос-Анджелес",
        description="Бесконечные кварталы между холмов",
        difficulty=2,
        category="city",
        country="США",
        region="Калифорния",
        continent="north_america",
        tags=["хайвеи"],
        longitude=-118.35,
        latitude=34.05,
        radius_km=22,
    ),
    ZoneSpec(
        name="Чикаго",
        description="Сетка, упирающаяся в озеро",
        difficulty=2,
        category="city",
        country="США",
        region="Иллинойс",
        continent="north_america",
        tags=["озеро", "сетка"],
        longitude=-87.65,
        latitude=41.88,
        radius_km=16,
    ),
    ZoneSpec(
        name="Гранд-Каньон",
        description="Каньон с террасами и петлями реки",
        difficulty=3,
        category="nature",
        country="США",
        region="Аризона",
        continent="north_america",
        tags=["каньон"],
        longitude=-112.1,
        latitude=36.1,
        radius_km=35,
    ),
    ZoneSpec(
        name="Долина Монументов",
        description="Одиночные останцы посреди плато",
        difficulty=3,
        category="desert",
        country="США",
        region="Юта",
        continent="north_america",
        tags=["останцы"],
        longitude=-110.1,
        latitude=36.98,
        radius_km=25,
    ),
    ZoneSpec(
        name="Йеллоустон",
        description="Гейзеры, озёра и обгоревший лес",
        difficulty=4,
        category="nature",
        country="США",
        region="Вайоминг",
        continent="north_america",
        tags=["гейзеры"],
        longitude=-110.5,
        latitude=44.6,
        radius_km=45,
    ),
    ZoneSpec(
        name="Флорида-Кис",
        description="Цепочка островов, связанных мостами",
        difficulty=3,
        category="islands",
        country="США",
        region="Флорида",
        continent="north_america",
        tags=["острова", "мосты"],
        longitude=-81.1,
        latitude=24.8,
        radius_km=45,
    ),
    ZoneSpec(
        name="Средний Запад, поля",
        description="Идеальные квадраты полей и круги орошения",
        difficulty=4,
        category="rural",
        country="США",
        region="Канзас",
        continent="north_america",
        tags=["квадраты", "круги"],
        longitude=-99.0,
        latitude=38.5,
        radius_km=60,
    ),
    ZoneSpec(
        name="Мехико",
        description="Огромный город в горной чаше",
        difficulty=2,
        category="city",
        country="Мексика",
        region="Мехико",
        continent="north_america",
        tags=["котловина"],
        longitude=-99.13,
        latitude=19.43,
        radius_km=20,
    ),
    ZoneSpec(
        name="Юкатан, сеноты",
        description="Плоские джунгли с круглыми провалами",
        difficulty=4,
        category="nature",
        country="Мексика",
        region="Юкатан",
        continent="north_america",
        tags=["сеноты", "джунгли"],
        longitude=-89.2,
        latitude=20.7,
        radius_km=45,
    ),
    ZoneSpec(
        name="Ванкувер",
        description="Город между морем и заснеженными горами",
        difficulty=2,
        category="coast",
        country="Канада",
        region="Британская Колумбия",
        continent="north_america",
        tags=["горы", "залив"],
        longitude=-123.12,
        latitude=49.28,
        radius_km=15,
    ),
    ZoneSpec(
        name="Канадские прерии",
        description="Расчерченные поля до горизонта",
        difficulty=5,
        category="rural",
        country="Канада",
        region="Саскачеван",
        continent="north_america",
        tags=["поля"],
        longitude=-106.0,
        latitude=51.5,
        radius_km=70,
    ),
    ZoneSpec(
        name="Гренландия, побережье",
        description="Ледник, обрывающийся в фьорды",
        difficulty=5,
        category="polar",
        country="Гренландия",
        region="Восточная Гренландия",
        continent="north_america",
        tags=["лёд", "фьорды"],
        longitude=-38.0,
        latitude=68.5,
        radius_km=80,
    ),
    ZoneSpec(
        name="Гавайи, Большой остров",
        description="Чёрная лава и зелёные склоны",
        difficulty=3,
        category="islands",
        country="США",
        region="Гавайи",
        continent="north_america",
        tags=["вулканы", "лава"],
        longitude=-155.5,
        latitude=19.6,
        radius_km=40,
    ),
    ZoneSpec(
        name="Рио-де-Жанейро",
        description="Скалы, пляжи и город между ними",
        difficulty=1,
        category="coast",
        country="Бразилия",
        region="Рио-де-Жанейро",
        continent="south_america",
        tags=["скалы", "пляжи"],
        longitude=-43.2,
        latitude=-22.91,
        radius_km=15,
    ),
    ZoneSpec(
        name="Амазонка, средняя",
        description="Река в сплошной сельве",
        difficulty=5,
        category="nature",
        country="Бразилия",
        region="Амазонас",
        continent="south_america",
        tags=["джунгли", "река"],
        longitude=-60.0,
        latitude=-3.5,
        radius_km=90,
    ),
    ZoneSpec(
        name="Мачу-Пикчу",
        description="Гребни хребтов и террасы над рекой",
        difficulty=4,
        category="historical",
        country="Перу",
        region="Куско",
        continent="south_america",
        tags=["Анды", "террасы"],
        longitude=-72.55,
        latitude=-13.16,
        radius_km=15,
    ),
    ZoneSpec(
        name="Атакама",
        description="Самая сухая пустыня с солончаками",
        difficulty=5,
        category="desert",
        country="Чили",
        region="Антофагаста",
        continent="south_america",
        tags=["солончаки"],
        longitude=-68.2,
        latitude=-23.5,
        radius_km=60,
    ),
    ZoneSpec(
        name="Салар-де-Уюни",
        description="Белая соляная равнина без ориентиров",
        difficulty=5,
        category="desert",
        country="Боливия",
        region="Потоси",
        continent="south_america",
        tags=["соль"],
        longitude=-67.5,
        latitude=-20.3,
        radius_km=55,
    ),
    ZoneSpec(
        name="Патагония, Торрес",
        description="Гранитные башни, ледники и озёра",
        difficulty=4,
        category="mountains",
        country="Чили",
        region="Магальянес",
        continent="south_america",
        tags=["ледники"],
        longitude=-73.0,
        latitude=-50.95,
        radius_km=40,
    ),
    ZoneSpec(
        name="Буэнос-Айрес",
        description="Сетка кварталов у широкой реки",
        difficulty=2,
        category="city",
        country="Аргентина",
        region="Буэнос-Айрес",
        continent="south_america",
        tags=["сетка", "Ла-Плата"],
        longitude=-58.44,
        latitude=-34.6,
        radius_km=18,
    ),
    ZoneSpec(
        name="Игуасу",
        description="Подкова водопадов в сельве",
        difficulty=3,
        category="nature",
        country="Аргентина",
        region="Мисьонес",
        continent="south_america",
        tags=["водопады"],
        longitude=-54.44,
        latitude=-25.69,
        radius_km=12,
    ),
    ZoneSpec(
        name="Галапагосы",
        description="Вулканические острова в океане",
        difficulty=4,
        category="islands",
        country="Эквадор",
        region="Галапагос",
        continent="south_america",
        tags=["вулканы", "острова"],
        longitude=-90.5,
        latitude=-0.5,
        radius_km=45,
    ),
    ZoneSpec(
        name="Пампа",
        description="Ровные поля и редкие рощи",
        difficulty=5,
        category="rural",
        country="Аргентина",
        region="Ла-Пампа",
        continent="south_america",
        tags=["поля"],
        longitude=-64.5,
        latitude=-36.5,
        radius_km=70,
    ),
    ZoneSpec(
        name="Сидней",
        description="Извилистая гавань и мосты",
        difficulty=1,
        category="coast",
        country="Австралия",
        region="Новый Южный Уэльс",
        continent="oceania",
        tags=["гавань"],
        longitude=151.21,
        latitude=-33.87,
        radius_km=16,
    ),
    ZoneSpec(
        name="Улуру",
        description="Одинокая красная скала на равнине",
        difficulty=2,
        category="desert",
        country="Австралия",
        region="Северная территория",
        continent="oceania",
        tags=["монолит"],
        longitude=131.04,
        latitude=-25.34,
        radius_km=15,
    ),
    ZoneSpec(
        name="Большой Барьерный риф",
        description="Пятна рифов в бирюзовой воде",
        difficulty=4,
        category="islands",
        country="Австралия",
        region="Квинсленд",
        continent="oceania",
        tags=["риф"],
        longitude=147.7,
        latitude=-18.5,
        radius_km=60,
    ),
    ZoneSpec(
        name="Мельбурн",
        description="Прямоугольная сетка и залив",
        difficulty=2,
        category="city",
        country="Австралия",
        region="Виктория",
        continent="oceania",
        tags=["сетка", "залив"],
        longitude=144.96,
        latitude=-37.81,
        radius_km=16,
    ),
    ZoneSpec(
        name="Аутбэк, Западная Австралия",
        description="Красная земля с полосами дюн",
        difficulty=5,
        category="desert",
        country="Австралия",
        region="Западная Австралия",
        continent="oceania",
        tags=["дюны", "пустошь"],
        longitude=123.0,
        latitude=-24.0,
        radius_km=90,
    ),
    ZoneSpec(
        name="Новая Зеландия, Южный остров",
        description="Заснеженные Альпы и озёра",
        difficulty=4,
        category="mountains",
        country="Новая Зеландия",
        region="Отаго",
        continent="oceania",
        tags=["горы", "озёра"],
        longitude=169.2,
        latitude=-44.6,
        radius_km=50,
    ),
    ZoneSpec(
        name="Бора-Бора",
        description="Кольцо рифа вокруг зелёного пика",
        difficulty=3,
        category="islands",
        country="Французская Полинезия",
        region="Общества",
        continent="oceania",
        tags=["атолл"],
        longitude=-151.74,
        latitude=-16.5,
        radius_km=12,
    ),
    ZoneSpec(
        name="Папуа, нагорье",
        description="Джунгли на изрезанных хребтах",
        difficulty=5,
        category="nature",
        country="Папуа — Новая Гвинея",
        region="Хайлендс",
        continent="oceania",
        tags=["джунгли", "хребты"],
        longitude=144.0,
        latitude=-5.8,
        radius_km=60,
    ),
    ZoneSpec(
        name="Антарктида, шельф Росса",
        description="Бесконечный лёд с трещинами",
        difficulty=5,
        category="polar",
        country="Антарктида",
        region="Земля Виктории",
        continent="antarctica",
        tags=["лёд", "шельф"],
        longitude=165.0,
        latitude=-77.5,
        radius_km=90,
    ),
    ZoneSpec(
        name="Антарктический полуостров",
        description="Ледники, сходящие в море",
        difficulty=5,
        category="polar",
        country="Антарктида",
        region="Земля Грейама",
        continent="antarctica",
        tags=["ледники"],
        longitude=-63.0,
        latitude=-65.0,
        radius_km=70,
    ),
]


async def seed(only_new: bool = False) -> tuple[int, int]:
    """Загрузить зоны. Возвращает количество добавленных и обновлённых."""
    added = updated = 0

    async with AsyncSessionLocal() as session:
        existing = {
            zone.name: zone
            for zone in (await session.execute(select(LocationZone))).scalars().all()
        }

        for spec in ZONES:
            zone = existing.get(spec.name)

            if zone is None:
                zone = LocationZone(name=spec.name, is_active=True)
                session.add(zone)
                added += 1
            elif only_new:
                continue
            else:
                updated += 1

            _apply(zone, spec)

        await session.commit()

    return added, updated


def _apply(zone: LocationZone, spec: ZoneSpec) -> None:
    zone.description = spec.description
    zone.difficulty = spec.difficulty
    zone.category = spec.category
    zone.country = spec.country
    zone.region = spec.region
    zone.continent = spec.continent
    zone.tags = json.dumps(spec.tags, ensure_ascii=False)
    zone.polygon = WKTElement(spec.polygon_wkt(), srid=4326)


def main() -> None:
    parser = argparse.ArgumentParser(description="Загрузка игровых зон Location King")
    parser.add_argument(
        "--only-new",
        action="store_true",
        help="не трогать зоны, которые уже есть в базе",
    )
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(levelname)-8s %(message)s")

    added, updated = asyncio.run(seed(only_new=args.only_new))
    logger.info(
        "Зоны загружены: добавлено %s, обновлено %s, всего в списке %s",
        added,
        updated,
        len(ZONES),
    )


if __name__ == "__main__":
    main()
