#!/usr/bin/env python3
"""
Загрузка игровых зон в базу.

Запускается сколько угодно раз: зоны сопоставляются по имени, существующие
обновляются, новые добавляются. Зона, которой в списке больше нет, не
удаляется, а помечается неактивной — раунды, уже сыгранные в ней, должны
остаться читаемыми.

Зона описывается центром и радиусом, а не готовым полигоном: так список
читается и правится, а квадрат вокруг центра для выбора случайной точки ничем
не хуже нарисованного вручную контура.

Список — только те места, где у провайдера есть настоящий снимок высокого
разрешения: города, побережья, известные объекты. Глубинка Сахары, Антарктида
и середина Амазонки выглядят на большом зуме размытой мозаикой Landsat, и
игрок справедливо считает, что игра сломалась.

    python scripts/seed.py
    python scripts/seed.py --only-new
"""

import argparse
import asyncio
import json
import logging
import math
import sys
from dataclasses import dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from geoalchemy2 import WKTElement
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import AsyncSessionLocal
from app.models.location_zone import LocationZone

logger = logging.getLogger("seed")

# Один градус широты — примерно столько километров
KM_PER_DEGREE = 111.19


@dataclass(frozen=True)
class ZoneSpec:
    """Описание зоны в списке ниже."""

    name: str
    description: str
    difficulty: int
    category: str
    country: str
    region: str
    continent: str
    tags: list[str]
    longitude: float
    latitude: float
    radius_km: float

    def polygon_wkt(self) -> str:
        """
        Квадрат вокруг центра.

        По долготе градус короче тем сильнее, чем ближе к полюсу, поэтому
        полуширина делится на косинус широты.
        """
        half_lat = self.radius_km / KM_PER_DEGREE
        cos_lat = max(abs(math.cos(math.radians(self.latitude))), 0.05)
        half_lon = half_lat / cos_lat

        west, east = self.longitude - half_lon, self.longitude + half_lon
        south, north = self.latitude - half_lat, self.latitude + half_lat

        corners = [(west, south), (west, north), (east, north), (east, south), (west, south)]
        points = ", ".join(f"{lon} {lat}" for lon, lat in corners)

        return f"POLYGON(({points}))"


ZONES: list[ZoneSpec] = [
    ZoneSpec(
        name="Москва, центр",
        description="Радиально-кольцевая планировка и излучина реки",
        difficulty=1,
        category="city",
        country="Россия",
        region="Москва",
        continent="europe",
        tags=["столица", "кольца"],
        longitude=37.62,
        latitude=55.75,
        radius_km=18,
    ),
    ZoneSpec(
        name="Санкт-Петербург",
        description="Каналы, Нева и прямоугольные кварталы",
        difficulty=1,
        category="city",
        country="Россия",
        region="Санкт-Петербург",
        continent="europe",
        tags=["каналы", "Нева"],
        longitude=30.32,
        latitude=59.94,
        radius_km=15,
    ),
    ZoneSpec(
        name="Париж",
        description="Плотная застройка, Сена и лучи проспектов",
        difficulty=1,
        category="city",
        country="Франция",
        region="Иль-де-Франс",
        continent="europe",
        tags=["столица", "Сена"],
        longitude=2.35,
        latitude=48.86,
        radius_km=10,
    ),
    ZoneSpec(
        name="Лондон",
        description="Темза и парки среди сплошной застройки",
        difficulty=1,
        category="city",
        country="Великобритания",
        region="Большой Лондон",
        continent="europe",
        tags=["столица", "Темза"],
        longitude=-0.13,
        latitude=51.51,
        radius_km=14,
    ),
    ZoneSpec(
        name="Берлин",
        description="Шпрее, Тиргартен и широкие магистрали",
        difficulty=1,
        category="city",
        country="Германия",
        region="Берлин",
        continent="europe",
        tags=["столица", "Шпрее"],
        longitude=13.4,
        latitude=52.52,
        radius_km=13,
    ),
    ZoneSpec(
        name="Рим",
        description="Тибр, античные площади и хаотичные кварталы",
        difficulty=2,
        category="historical",
        country="Италия",
        region="Лацио",
        continent="europe",
        tags=["античность", "Тибр"],
        longitude=12.5,
        latitude=41.9,
        radius_km=10,
    ),
    ZoneSpec(
        name="Барселона",
        description="Квадратная сетка Эшампле у самого моря",
        difficulty=1,
        category="city",
        country="Испания",
        region="Каталония",
        continent="europe",
        tags=["сетка", "море"],
        longitude=2.17,
        latitude=41.39,
        radius_km=8,
    ),
    ZoneSpec(
        name="Амстердам",
        description="Полукольца каналов и узкие кварталы",
        difficulty=1,
        category="city",
        country="Нидерланды",
        region="Северная Голландия",
        continent="europe",
        tags=["каналы"],
        longitude=4.9,
        latitude=52.37,
        radius_km=7,
    ),
    ZoneSpec(
        name="Венеция",
        description="Острова лагуны, прорезанные каналами",
        difficulty=1,
        category="coast",
        country="Италия",
        region="Венето",
        continent="europe",
        tags=["лагуна", "острова"],
        longitude=12.33,
        latitude=45.44,
        radius_km=5,
    ),
    ZoneSpec(
        name="Стокгольм",
        description="Город на островах между озером и морем",
        difficulty=2,
        category="coast",
        country="Швеция",
        region="Стокгольм",
        continent="europe",
        tags=["острова", "шхеры"],
        longitude=18.07,
        latitude=59.33,
        radius_km=12,
    ),
    ZoneSpec(
        name="Прага",
        description="Влтава и плотный исторический центр",
        difficulty=2,
        category="historical",
        country="Чехия",
        region="Прага",
        continent="europe",
        tags=["Влтава"],
        longitude=14.42,
        latitude=50.09,
        radius_km=8,
    ),
    ZoneSpec(
        name="Вена",
        description="Дунай и кольцо бульваров",
        difficulty=2,
        category="city",
        country="Австрия",
        region="Вена",
        continent="europe",
        tags=["Дунай", "кольцо"],
        longitude=16.37,
        latitude=48.21,
        radius_km=10,
    ),
    ZoneSpec(
        name="Афины",
        description="Плотная застройка между холмами и морем",
        difficulty=2,
        category="historical",
        country="Греция",
        region="Аттика",
        continent="europe",
        tags=["античность"],
        longitude=23.73,
        latitude=37.98,
        radius_km=10,
    ),
    ZoneSpec(
        name="Швейцарские Альпы",
        description="Ледники, узкие долины и серпантины",
        difficulty=4,
        category="mountains",
        country="Швейцария",
        region="Вале",
        continent="europe",
        tags=["горы", "ледники"],
        longitude=7.85,
        latitude=46.1,
        radius_km=45,
    ),
    ZoneSpec(
        name="Норвежские фьорды",
        description="Узкие заливы между отвесными склонами",
        difficulty=4,
        category="coast",
        country="Норвегия",
        region="Вестланд",
        continent="europe",
        tags=["фьорды"],
        longitude=6.5,
        latitude=61.2,
        radius_km=55,
    ),
    ZoneSpec(
        name="Исландия, юг",
        description="Чёрные пески, ледники и лавовые поля",
        difficulty=5,
        category="nature",
        country="Исландия",
        region="Сюдюрланд",
        continent="europe",
        tags=["вулканы", "ледники"],
        longitude=-19.0,
        latitude=63.7,
        radius_km=60,
    ),
    ZoneSpec(
        name="Тоскана",
        description="Холмы, виноградники и вытянутые фермы",
        difficulty=3,
        category="rural",
        country="Италия",
        region="Тоскана",
        continent="europe",
        tags=["холмы", "поля"],
        longitude=11.3,
        latitude=43.4,
        radius_km=40,
    ),
    ZoneSpec(
        name="Нидерланды, польдеры",
        description="Идеально прямые каналы и прямоугольные поля",
        difficulty=3,
        category="rural",
        country="Нидерланды",
        region="Флеволанд",
        continent="europe",
        tags=["польдеры", "каналы"],
        longitude=5.6,
        latitude=52.5,
        radius_km=35,
    ),
    ZoneSpec(
        name="Рурский бассейн",
        description="Заводы, отвалы и плотная сеть дорог",
        difficulty=4,
        category="industrial",
        country="Германия",
        region="Северный Рейн — Вестфалия",
        continent="europe",
        tags=["заводы"],
        longitude=7.1,
        latitude=51.5,
        radius_km=30,
    ),
    ZoneSpec(
        name="Шотландское высокогорье",
        description="Голые склоны, озёра и почти нет дорог",
        difficulty=4,
        category="mountains",
        country="Великобритания",
        region="Хайленд",
        continent="europe",
        tags=["озёра", "вереск"],
        longitude=-4.8,
        latitude=57.2,
        radius_km=55,
    ),
    ZoneSpec(
        name="Крымское побережье",
        description="Горы, спускающиеся к морю",
        difficulty=3,
        category="coast",
        country="Россия",
        region="Крым",
        continent="europe",
        tags=["море", "горы"],
        longitude=34.2,
        latitude=44.55,
        radius_km=30,
    ),
    ZoneSpec(
        name="Сочи, побережье",
        description="Полоса города между морем и хребтом",
        difficulty=2,
        category="coast",
        country="Россия",
        region="Краснодарский край",
        continent="europe",
        tags=["море", "горы"],
        longitude=39.75,
        latitude=43.58,
        radius_km=18,
    ),
    ZoneSpec(
        name="Казань",
        description="Кремль, слияние рек и новые кварталы",
        difficulty=2,
        category="city",
        country="Россия",
        region="Татарстан",
        continent="europe",
        tags=["реки"],
        longitude=49.11,
        latitude=55.79,
        radius_km=14,
    ),
    ZoneSpec(
        name="Токио",
        description="Бесконечная застройка вокруг залива",
        difficulty=2,
        category="city",
        country="Япония",
        region="Канто",
        continent="asia",
        tags=["столица", "залив"],
        longitude=139.7,
        latitude=35.69,
        radius_km=20,
    ),
    ZoneSpec(
        name="Киото",
        description="Прямоугольная сетка в кольце гор",
        difficulty=2,
        category="historical",
        country="Япония",
        region="Кансай",
        continent="asia",
        tags=["сетка", "храмы"],
        longitude=135.77,
        latitude=35.01,
        radius_km=10,
    ),
    ZoneSpec(
        name="Пекин",
        description="Концентрические кольца вокруг запретного города",
        difficulty=2,
        category="city",
        country="Китай",
        region="Пекин",
        continent="asia",
        tags=["кольца"],
        longitude=116.4,
        latitude=39.9,
        radius_km=20,
    ),
    ZoneSpec(
        name="Шанхай",
        description="Небоскрёбы и петля Хуанпу",
        difficulty=2,
        category="city",
        country="Китай",
        region="Шанхай",
        continent="asia",
        tags=["река", "высотки"],
        longitude=121.47,
        latitude=31.23,
        radius_km=18,
    ),
    ZoneSpec(
        name="Гонконг",
        description="Высотки, зажатые между сопками и морем",
        difficulty=2,
        category="city",
        country="Китай",
        region="Гонконг",
        continent="asia",
        tags=["высотки", "море"],
        longitude=114.17,
        latitude=22.32,
        radius_km=10,
    ),
    ZoneSpec(
        name="Сингапур",
        description="Остров-город с намывными берегами",
        difficulty=2,
        category="city",
        country="Сингапур",
        region="Сингапур",
        continent="asia",
        tags=["остров", "порт"],
        longitude=103.82,
        latitude=1.35,
        radius_km=12,
    ),
    ZoneSpec(
        name="Дубай",
        description="Пальмовые острова и прямые магистрали в пустыне",
        difficulty=1,
        category="architecture",
        country="ОАЭ",
        region="Дубай",
        continent="asia",
        tags=["намыв", "пустыня"],
        longitude=55.27,
        latitude=25.2,
        radius_km=18,
    ),
    ZoneSpec(
        name="Стамбул",
        description="Пролив, разрезающий город надвое",
        difficulty=1,
        category="city",
        country="Турция",
        region="Мармара",
        continent="asia",
        tags=["Босфор"],
        longitude=28.98,
        latitude=41.01,
        radius_km=18,
    ),
    ZoneSpec(
        name="Иерусалим",
        description="Плотный старый город на холмах",
        difficulty=3,
        category="historical",
        country="Израиль",
        region="Иерусалим",
        continent="asia",
        tags=["холмы"],
        longitude=35.22,
        latitude=31.78,
        radius_km=8,
    ),
    ZoneSpec(
        name="Гималаи, Кхумбу",
        description="Снежные хребты и ледники",
        difficulty=5,
        category="mountains",
        country="Непал",
        region="Кхумбу",
        continent="asia",
        tags=["горы", "снег"],
        longitude=86.9,
        latitude=27.9,
        radius_km=45,
    ),
    ZoneSpec(
        name="Рисовые террасы Ифугао",
        description="Ступени полей по склонам",
        difficulty=4,
        category="rural",
        country="Филиппины",
        region="Лусон",
        continent="asia",
        tags=["террасы", "рис"],
        longitude=121.1,
        latitude=16.93,
        radius_km=25,
    ),
    ZoneSpec(
        name="Дельта Меконга",
        description="Сеть проток и рисовых полей",
        difficulty=4,
        category="rural",
        country="Вьетнам",
        region="Меконг",
        continent="asia",
        tags=["протоки", "рис"],
        longitude=105.8,
        latitude=10.2,
        radius_km=60,
    ),
    ZoneSpec(
        name="Дели",
        description="Плотная застройка и радиальные проспекты",
        difficulty=2,
        category="city",
        country="Индия",
        region="Дели",
        continent="asia",
        tags=["столица"],
        longitude=77.21,
        latitude=28.61,
        radius_km=20,
    ),
    ZoneSpec(
        name="Мумбаи",
        description="Полуостров, застроенный целиком",
        difficulty=2,
        category="city",
        country="Индия",
        region="Махараштра",
        continent="asia",
        tags=["полуостров"],
        longitude=72.85,
        latitude=19.08,
        radius_km=15,
    ),
    ZoneSpec(
        name="Сеул",
        description="Река Ханган между горными кварталами",
        difficulty=2,
        category="city",
        country="Южная Корея",
        region="Сеул",
        continent="asia",
        tags=["река", "горы"],
        longitude=126.98,
        latitude=37.57,
        radius_km=16,
    ),
    ZoneSpec(
        name="Бангкок",
        description="Изгибы Чаопхрайи среди сплошной застройки",
        difficulty=2,
        category="city",
        country="Таиланд",
        region="Бангкок",
        continent="asia",
        tags=["река"],
        longitude=100.5,
        latitude=13.75,
        radius_km=16,
    ),
    ZoneSpec(
        name="Долина Царей",
        description="Скалы и русла посреди пустыни у Нила",
        difficulty=3,
        category="historical",
        country="Египет",
        region="Луксор",
        continent="asia",
        tags=["археология", "Нил"],
        longitude=32.6,
        latitude=25.74,
        radius_km=12,
    ),
    ZoneSpec(
        name="Каир",
        description="Плотный город на обоих берегах Нила",
        difficulty=2,
        category="city",
        country="Египет",
        region="Каир",
        continent="africa",
        tags=["Нил", "столица"],
        longitude=31.24,
        latitude=30.05,
        radius_km=18,
    ),
    ZoneSpec(
        name="Пирамиды Гизы",
        description="Правильные треугольники на краю песков",
        difficulty=1,
        category="historical",
        country="Египет",
        region="Гиза",
        continent="africa",
        tags=["пирамиды"],
        longitude=31.13,
        latitude=29.98,
        radius_km=6,
    ),
    ZoneSpec(
        name="Кейптаун",
        description="Город между столовой горой и двумя океанами",
        difficulty=2,
        category="coast",
        country="ЮАР",
        region="Западный Кейп",
        continent="africa",
        tags=["гора", "океан"],
        longitude=18.42,
        latitude=-33.92,
        radius_km=15,
    ),
    ZoneSpec(
        name="Килиманджаро",
        description="Одинокий конус над саванной",
        difficulty=4,
        category="mountains",
        country="Танзания",
        region="Килиманджаро",
        continent="africa",
        tags=["вулкан"],
        longitude=37.35,
        latitude=-3.07,
        radius_km=25,
    ),
    ZoneSpec(
        name="Марракеш",
        description="Глиняный старый город у подножия Атласа",
        difficulty=3,
        category="city",
        country="Марокко",
        region="Марракеш",
        continent="africa",
        tags=["медина"],
        longitude=-7.99,
        latitude=31.63,
        radius_km=10,
    ),
    ZoneSpec(
        name="Виктория, водопад",
        description="Разлом, куда обрушивается река",
        difficulty=3,
        category="nature",
        country="Замбия",
        region="Ливингстон",
        continent="africa",
        tags=["водопад"],
        longitude=25.86,
        latitude=-17.92,
        radius_km=12,
    ),
    ZoneSpec(
        name="Дельта Нила",
        description="Веер проток и сплошные поля",
        difficulty=3,
        category="rural",
        country="Египет",
        region="Дельта",
        continent="africa",
        tags=["дельта", "поля"],
        longitude=31.2,
        latitude=30.9,
        radius_km=55,
    ),
    ZoneSpec(
        name="Найроби",
        description="Город на краю национального парка",
        difficulty=3,
        category="city",
        country="Кения",
        region="Найроби",
        continent="africa",
        tags=["саванна"],
        longitude=36.82,
        latitude=-1.29,
        radius_km=14,
    ),
    ZoneSpec(
        name="Нью-Йорк, Манхэттен",
        description="Прямоугольная сетка и зелёный прямоугольник парка",
        difficulty=1,
        category="city",
        country="США",
        region="Нью-Йорк",
        continent="north_america",
        tags=["сетка", "парк"],
        longitude=-73.97,
        latitude=40.78,
        radius_km=10,
    ),
    ZoneSpec(
        name="Сан-Франциско",
        description="Сетка улиц на холмах у залива",
        difficulty=1,
        category="city",
        country="США",
        region="Калифорния",
        continent="north_america",
        tags=["холмы", "залив"],
        longitude=-122.44,
        latitude=37.76,
        radius_km=10,
    ),
    ZoneSpec(
        name="Лос-Анджелес",
        description="Бесконечные кварталы между холмов",
        difficulty=2,
        category="city",
        country="США",
        region="Калифорния",
        continent="north_america",
        tags=["хайвеи"],
        longitude=-118.35,
        latitude=34.05,
        radius_km=22,
    ),
    ZoneSpec(
        name="Чикаго",
        description="Сетка, упирающаяся в озеро",
        difficulty=2,
        category="city",
        country="США",
        region="Иллинойс",
        continent="north_america",
        tags=["озеро", "сетка"],
        longitude=-87.65,
        latitude=41.88,
        radius_km=16,
    ),
    ZoneSpec(
        name="Гранд-Каньон",
        description="Каньон с террасами и петлями реки",
        difficulty=3,
        category="nature",
        country="США",
        region="Аризона",
        continent="north_america",
        tags=["каньон"],
        longitude=-112.1,
        latitude=36.1,
        radius_km=35,
    ),
    ZoneSpec(
        name="Долина Монументов",
        description="Одиночные останцы посреди плато",
        difficulty=3,
        category="desert",
        country="США",
        region="Юта",
        continent="north_america",
        tags=["останцы"],
        longitude=-110.1,
        latitude=36.98,
        radius_km=25,
    ),
    ZoneSpec(
        name="Йеллоустон",
        description="Гейзеры, озёра и обгоревший лес",
        difficulty=4,
        category="nature",
        country="США",
        region="Вайоминг",
        continent="north_america",
        tags=["гейзеры"],
        longitude=-110.5,
        latitude=44.6,
        radius_km=45,
    ),
    ZoneSpec(
        name="Флорида-Кис",
        description="Цепочка островов, связанных мостами",
        difficulty=3,
        category="islands",
        country="США",
        region="Флорида",
        continent="north_america",
        tags=["острова", "мосты"],
        longitude=-81.1,
        latitude=24.8,
        radius_km=45,
    ),
    ZoneSpec(
        name="Средний Запад, поля",
        description="Идеальные квадраты полей и круги орошения",
        difficulty=4,
        category="rural",
        country="США",
        region="Канзас",
        continent="north_america",
        tags=["квадраты", "круги"],
        longitude=-99.0,
        latitude=38.5,
        radius_km=60,
    ),
    ZoneSpec(
        name="Мехико",
        description="Огромный город в горной чаше",
        difficulty=2,
        category="city",
        country="Мексика",
        region="Мехико",
        continent="north_america",
        tags=["котловина"],
        longitude=-99.13,
        latitude=19.43,
        radius_km=20,
    ),
    ZoneSpec(
        name="Юкатан, сеноты",
        description="Плоские джунгли с круглыми провалами",
        difficulty=4,
        category="nature",
        country="Мексика",
        region="Юкатан",
        continent="north_america",
        tags=["сеноты", "джунгли"],
        longitude=-89.2,
        latitude=20.7,
        radius_km=45,
    ),
    ZoneSpec(
        name="Ванкувер",
        description="Город между морем и заснеженными горами",
        difficulty=2,
        category="coast",
        country="Канада",
        region="Британская Колумбия",
        continent="north_america",
        tags=["горы", "залив"],
        longitude=-123.12,
        latitude=49.28,
        radius_km=15,
    ),
    ZoneSpec(
        name="Гавайи, Большой остров",
        description="Чёрная лава и зелёные склоны",
        difficulty=3,
        category="islands",
        country="США",
        region="Гавайи",
        continent="north_america",
        tags=["вулканы", "лава"],
        longitude=-155.5,
        latitude=19.6,
        radius_km=40,
    ),
    ZoneSpec(
        name="Рио-де-Жанейро",
        description="Скалы, пляжи и город между ними",
        difficulty=1,
        category="coast",
        country="Бразилия",
        region="Рио-де-Жанейро",
        continent="south_america",
        tags=["скалы", "пляжи"],
        longitude=-43.2,
        latitude=-22.91,
        radius_km=15,
    ),
    ZoneSpec(
        name="Мачу-Пикчу",
        description="Гребни хребтов и террасы над рекой",
        difficulty=4,
        category="historical",
        country="Перу",
        region="Куско",
        continent="south_america",
        tags=["Анды", "террасы"],
        longitude=-72.55,
        latitude=-13.16,
        radius_km=15,
    ),
    ZoneSpec(
        name="Патагония, Торрес",
        description="Гранитные башни, ледники и озёра",
        difficulty=4,
        category="mountains",
        country="Чили",
        region="Магальянес",
        continent="south_america",
        tags=["ледники"],
        longitude=-73.0,
        latitude=-50.95,
        radius_km=40,
    ),
    ZoneSpec(
        name="Буэнос-Айрес",
        description="Сетка кварталов у широкой реки",
        difficulty=2,
        category="city",
        country="Аргентина",
        region="Буэнос-Айрес",
        continent="south_america",
        tags=["сетка", "Ла-Плата"],
        longitude=-58.44,
        latitude=-34.6,
        radius_km=18,
    ),
    ZoneSpec(
        name="Игуасу",
        description="Подкова водопадов в сельве",
        difficulty=3,
        category="nature",
        country="Аргентина",
        region="Мисьонес",
        continent="south_america",
        tags=["водопады"],
        longitude=-54.44,
        latitude=-25.69,
        radius_km=12,
    ),
    ZoneSpec(
        name="Сидней",
        description="Извилистая гавань и мосты",
        difficulty=1,
        category="coast",
        country="Австралия",
        region="Новый Южный Уэльс",
        continent="oceania",
        tags=["гавань"],
        longitude=151.21,
        latitude=-33.87,
        radius_km=16,
    ),
    ZoneSpec(
        name="Улуру",
        description="Одинокая красная скала на равнине",
        difficulty=2,
        category="desert",
        country="Австралия",
        region="Северная территория",
        continent="oceania",
        tags=["монолит"],
        longitude=131.04,
        latitude=-25.34,
        radius_km=15,
    ),
    ZoneSpec(
        name="Большой Барьерный риф",
        description="Пятна рифов в бирюзовой воде",
        difficulty=4,
        category="islands",
        country="Австралия",
        region="Квинсленд",
        continent="oceania",
        tags=["риф"],
        longitude=147.7,
        latitude=-18.5,
        radius_km=60,
    ),
    ZoneSpec(
        name="Мельбурн",
        description="Прямоугольная сетка и залив",
        difficulty=2,
        category="city",
        country="Австралия",
        region="Виктория",
        continent="oceania",
        tags=["сетка", "залив"],
        longitude=144.96,
        latitude=-37.81,
        radius_km=16,
    ),
    ZoneSpec(
        name="Новая Зеландия, Южный остров",
        description="Заснеженные Альпы и озёра",
        difficulty=4,
        category="mountains",
        country="Новая Зеландия",
        region="Отаго",
        continent="oceania",
        tags=["горы", "озёра"],
        longitude=169.2,
        latitude=-44.6,
        radius_km=50,
    ),
    ZoneSpec(
        name="Бора-Бора",
        description="Кольцо рифа вокруг зелёного пика",
        difficulty=3,
        category="islands",
        country="Французская Полинезия",
        region="Общества",
        continent="oceania",
        tags=["атолл"],
        longitude=-151.74,
        latitude=-16.5,
        radius_km=12,
    ),
    ZoneSpec(
        name="Мадрид",
        description="Строгая сетка кварталов и парк Ретиро",
        difficulty=2,
        category="city",
        country="Испания",
        region="Мадрид",
        continent="europe",
        tags=["столица"],
        longitude=-3.7,
        latitude=40.42,
        radius_km=12,
    ),
    ZoneSpec(
        name="Милан",
        description="Кольца улиц вокруг собора и стадион Сан-Сиро",
        difficulty=2,
        category="city",
        country="Италия",
        region="Ломбардия",
        continent="europe",
        tags=["мода"],
        longitude=9.19,
        latitude=45.46,
        radius_km=10,
    ),
    ZoneSpec(
        name="Мюнхен",
        description="Олимпийский парк и излучина Изара",
        difficulty=2,
        category="city",
        country="Германия",
        region="Бавария",
        continent="europe",
        tags=["Бавария"],
        longitude=11.58,
        latitude=48.14,
        radius_km=12,
    ),
    ZoneSpec(
        name="Гамбург",
        description="Порт, доки и озеро Альстер",
        difficulty=2,
        category="city",
        country="Германия",
        region="Гамбург",
        continent="europe",
        tags=["порт"],
        longitude=10.0,
        latitude=53.55,
        radius_km=12,
    ),
    ZoneSpec(
        name="Копенгаген",
        description="Каналы, гавань и мост в Мальмё",
        difficulty=2,
        category="city",
        country="Дания",
        region="Столичная область",
        continent="europe",
        tags=["каналы"],
        longitude=12.57,
        latitude=55.68,
        radius_km=10,
    ),
    ZoneSpec(
        name="Осло",
        description="Фьорд, врезающийся в город",
        difficulty=2,
        category="city",
        country="Норвегия",
        region="Осло",
        continent="europe",
        tags=["фьорд"],
        longitude=10.75,
        latitude=59.91,
        radius_km=12,
    ),
    ZoneSpec(
        name="Хельсинки",
        description="Полуостров, шхеры и Суоменлинна",
        difficulty=3,
        category="city",
        country="Финляндия",
        region="Уусимаа",
        continent="europe",
        tags=["шхеры"],
        longitude=24.94,
        latitude=60.17,
        radius_km=12,
    ),
    ZoneSpec(
        name="Варшава",
        description="Висла и высотки в центре",
        difficulty=2,
        category="city",
        country="Польша",
        region="Мазовия",
        continent="europe",
        tags=["Висла"],
        longitude=21.01,
        latitude=52.23,
        radius_km=12,
    ),
    ZoneSpec(
        name="Будапешт",
        description="Дунай разрезает город надвое",
        difficulty=2,
        category="city",
        country="Венгрия",
        region="Будапешт",
        continent="europe",
        tags=["Дунай"],
        longitude=19.04,
        latitude=47.5,
        radius_km=11,
    ),
    ZoneSpec(
        name="Лиссабон",
        description="Холмы, мост 25 апреля и устье Тежу",
        difficulty=2,
        category="city",
        country="Португалия",
        region="Лиссабон",
        continent="europe",
        tags=["мост"],
        longitude=-9.14,
        latitude=38.72,
        radius_km=11,
    ),
    ZoneSpec(
        name="Дублин",
        description="Залив и река Лиффи",
        difficulty=3,
        category="city",
        country="Ирландия",
        region="Ленстер",
        continent="europe",
        tags=["залив"],
        longitude=-6.26,
        latitude=53.35,
        radius_km=10,
    ),
    ZoneSpec(
        name="Брюссель",
        description="Кольцевая и парки в центре",
        difficulty=3,
        category="city",
        country="Бельгия",
        region="Брюссель",
        continent="europe",
        tags=["кольцо"],
        longitude=4.35,
        latitude=50.85,
        radius_km=10,
    ),
    ZoneSpec(
        name="Цюрих",
        description="Озеро и город у его начала",
        difficulty=3,
        category="city",
        country="Швейцария",
        region="Цюрих",
        continent="europe",
        tags=["озеро"],
        longitude=8.54,
        latitude=47.37,
        radius_km=9,
    ),
    ZoneSpec(
        name="Неаполь",
        description="Залив и Везувий рядом",
        difficulty=2,
        category="city",
        country="Италия",
        region="Кампания",
        continent="europe",
        tags=["вулкан"],
        longitude=14.27,
        latitude=40.85,
        radius_km=12,
    ),
    ZoneSpec(
        name="Эдинбург",
        description="Замковая скала и вулкан Артурово Кресло",
        difficulty=3,
        category="city",
        country="Великобритания",
        region="Шотландия",
        continent="europe",
        tags=["замок"],
        longitude=-3.19,
        latitude=55.95,
        radius_km=9,
    ),
    ZoneSpec(
        name="Марсель",
        description="Старый порт и известняковые каланки",
        difficulty=3,
        category="city",
        country="Франция",
        region="Прованс",
        continent="europe",
        tags=["порт"],
        longitude=5.37,
        latitude=43.3,
        radius_km=12,
    ),
    ZoneSpec(
        name="Роттердам",
        description="Порт и разводные мосты",
        difficulty=3,
        category="city",
        country="Нидерланды",
        region="Южная Голландия",
        continent="europe",
        tags=["порт"],
        longitude=4.48,
        latitude=51.92,
        radius_km=12,
    ),
    ZoneSpec(
        name="Минск",
        description="Проспекты и Свислочь",
        difficulty=3,
        category="city",
        country="Беларусь",
        region="Минск",
        continent="europe",
        tags=["проспекты"],
        longitude=27.56,
        latitude=53.9,
        radius_km=12,
    ),
    ZoneSpec(
        name="Киев",
        description="Днепр и правобережные холмы",
        difficulty=2,
        category="city",
        country="Украина",
        region="Киев",
        continent="europe",
        tags=["Днепр"],
        longitude=30.52,
        latitude=50.45,
        radius_km=14,
    ),
    ZoneSpec(
        name="Калининград",
        description="Кольцо фортов и остров Канта",
        difficulty=3,
        category="city",
        country="Россия",
        region="Калининградская область",
        continent="europe",
        tags=["форты"],
        longitude=20.51,
        latitude=54.71,
        radius_km=9,
    ),
    ZoneSpec(
        name="Нижний Новгород",
        description="Слияние Оки и Волги",
        difficulty=3,
        category="city",
        country="Россия",
        region="Нижегородская область",
        continent="europe",
        tags=["слияние"],
        longitude=44.0,
        latitude=56.33,
        radius_km=12,
    ),
    ZoneSpec(
        name="Екатеринбург",
        description="Пруд в центре и башни Сити",
        difficulty=3,
        category="city",
        country="Россия",
        region="Свердловская область",
        continent="asia",
        tags=["Урал"],
        longitude=60.61,
        latitude=56.84,
        radius_km=12,
    ),
    ZoneSpec(
        name="Новосибирск",
        description="Обь и мосты через неё",
        difficulty=3,
        category="city",
        country="Россия",
        region="Новосибирская область",
        continent="asia",
        tags=["Обь"],
        longitude=82.92,
        latitude=55.03,
        radius_km=14,
    ),
    ZoneSpec(
        name="Владивосток",
        description="Бухта Золотой Рог и вантовые мосты",
        difficulty=3,
        category="city",
        country="Россия",
        region="Приморский край",
        continent="asia",
        tags=["мосты"],
        longitude=131.89,
        latitude=43.12,
        radius_km=10,
    ),
    ZoneSpec(
        name="Торонто",
        description="Башня Си-Эн и берег Онтарио",
        difficulty=2,
        category="city",
        country="Канада",
        region="Онтарио",
        continent="north_america",
        tags=["озеро"],
        longitude=-79.38,
        latitude=43.65,
        radius_km=12,
    ),
    ZoneSpec(
        name="Монреаль",
        description="Остров на реке Святого Лаврентия",
        difficulty=3,
        category="city",
        country="Канада",
        region="Квебек",
        continent="north_america",
        tags=["остров"],
        longitude=-73.57,
        latitude=45.5,
        radius_km=12,
    ),
    ZoneSpec(
        name="Бостон",
        description="Извилистые улицы и гавань",
        difficulty=2,
        category="city",
        country="США",
        region="Массачусетс",
        continent="north_america",
        tags=["гавань"],
        longitude=-71.06,
        latitude=42.36,
        radius_km=10,
    ),
    ZoneSpec(
        name="Сиэтл",
        description="Залив Пьюджет-Саунд и озеро Вашингтон",
        difficulty=2,
        category="city",
        country="США",
        region="Вашингтон",
        continent="north_america",
        tags=["залив"],
        longitude=-122.33,
        latitude=47.61,
        radius_km=12,
    ),
    ZoneSpec(
        name="Майами",
        description="Пляжи, каналы и намывные острова",
        difficulty=1,
        category="city",
        country="США",
        region="Флорида",
        continent="north_america",
        tags=["пляжи"],
        longitude=-80.19,
        latitude=25.77,
        radius_km=12,
    ),
    ZoneSpec(
        name="Лас-Вегас",
        description="Сетка кварталов посреди пустыни",
        difficulty=1,
        category="city",
        country="США",
        region="Невада",
        continent="north_america",
        tags=["пустыня"],
        longitude=-115.14,
        latitude=36.17,
        radius_km=14,
    ),
    ZoneSpec(
        name="Сан-Диего",
        description="Бухта, авиабазы и граница",
        difficulty=2,
        category="city",
        country="США",
        region="Калифорния",
        continent="north_america",
        tags=["бухта"],
        longitude=-117.16,
        latitude=32.72,
        radius_km=12,
    ),
    ZoneSpec(
        name="Сантьяго",
        description="Город у стены Анд",
        difficulty=3,
        category="city",
        country="Чили",
        region="Столичная область",
        continent="south_america",
        tags=["Анды"],
        longitude=-70.65,
        latitude=-33.45,
        radius_km=14,
    ),
    ZoneSpec(
        name="Лима",
        description="Обрыв над океаном и пустынные окраины",
        difficulty=3,
        category="city",
        country="Перу",
        region="Лима",
        continent="south_america",
        tags=["океан"],
        longitude=-77.04,
        latitude=-12.05,
        radius_km=14,
    ),
    ZoneSpec(
        name="Богота",
        description="Плато на высоте и горы с востока",
        difficulty=3,
        category="city",
        country="Колумбия",
        region="Кундинамарка",
        continent="south_america",
        tags=["плато"],
        longitude=-74.07,
        latitude=4.71,
        radius_km=14,
    ),
    ZoneSpec(
        name="Осака",
        description="Каналы, порт и замок в центре",
        difficulty=2,
        category="city",
        country="Япония",
        region="Кансай",
        continent="asia",
        tags=["каналы"],
        longitude=135.5,
        latitude=34.69,
        radius_km=12,
    ),
    ZoneSpec(
        name="Тайбэй",
        description="Котловина между гор и башня 101",
        difficulty=3,
        category="city",
        country="Тайвань",
        region="Тайбэй",
        continent="asia",
        tags=["башня"],
        longitude=121.56,
        latitude=25.03,
        radius_km=11,
    ),
    ZoneSpec(
        name="Гуанчжоу",
        description="Жемчужная река и небоскрёбы",
        difficulty=3,
        category="city",
        country="Китай",
        region="Гуандун",
        continent="asia",
        tags=["река"],
        longitude=113.26,
        latitude=23.13,
        radius_km=14,
    ),
    ZoneSpec(
        name="Шэньчжэнь",
        description="Город, выросший за сорок лет",
        difficulty=3,
        category="city",
        country="Китай",
        region="Гуандун",
        continent="asia",
        tags=["новостройки"],
        longitude=114.06,
        latitude=22.54,
        radius_km=14,
    ),
    ZoneSpec(
        name="Куала-Лумпур",
        description="Башни Петронас среди зелени",
        difficulty=2,
        category="city",
        country="Малайзия",
        region="Куала-Лумпур",
        continent="asia",
        tags=["башни"],
        longitude=101.69,
        latitude=3.14,
        radius_km=12,
    ),
    ZoneSpec(
        name="Джакарта",
        description="Плотная застройка и каналы к морю",
        difficulty=3,
        category="city",
        country="Индонезия",
        region="Джакарта",
        continent="asia",
        tags=["каналы"],
        longitude=106.85,
        latitude=-6.21,
        radius_km=14,
    ),
    ZoneSpec(
        name="Манила",
        description="Залив и река Пасиг",
        difficulty=3,
        category="city",
        country="Филиппины",
        region="Метро Манила",
        continent="asia",
        tags=["залив"],
        longitude=120.98,
        latitude=14.6,
        radius_km=12,
    ),
    ZoneSpec(
        name="Ханой",
        description="Озёра в центре и Красная река",
        difficulty=3,
        category="city",
        country="Вьетнам",
        region="Ханой",
        continent="asia",
        tags=["озёра"],
        longitude=105.83,
        latitude=21.03,
        radius_km=12,
    ),
    ZoneSpec(
        name="Хошимин",
        description="Изгибы Сайгона и плотные кварталы",
        difficulty=3,
        category="city",
        country="Вьетнам",
        region="Хошимин",
        continent="asia",
        tags=["река"],
        longitude=106.7,
        latitude=10.78,
        radius_km=12,
    ),
    ZoneSpec(
        name="Тель-Авив",
        description="Прямая линия побережья и Яффа",
        difficulty=2,
        category="city",
        country="Израиль",
        region="Тель-Авив",
        continent="asia",
        tags=["побережье"],
        longitude=34.78,
        latitude=32.08,
        radius_km=9,
    ),
    ZoneSpec(
        name="Доха",
        description="Полумесяц набережной Корниш",
        difficulty=2,
        category="city",
        country="Катар",
        region="Доха",
        continent="asia",
        tags=["залив"],
        longitude=51.53,
        latitude=25.29,
        radius_km=12,
    ),
    ZoneSpec(
        name="Эр-Рияд",
        description="Сетка кварталов и вади посреди песка",
        difficulty=3,
        category="city",
        country="Саудовская Аравия",
        region="Эр-Рияд",
        continent="asia",
        tags=["пустыня"],
        longitude=46.72,
        latitude=24.71,
        radius_km=16,
    ),
    ZoneSpec(
        name="Алматы",
        description="Улицы под склоном Заилийского Алатау",
        difficulty=3,
        category="city",
        country="Казахстан",
        region="Алматы",
        continent="asia",
        tags=["горы"],
        longitude=76.89,
        latitude=43.24,
        radius_km=12,
    ),
    ZoneSpec(
        name="Ташкент",
        description="Широкие проспекты и каналы",
        difficulty=3,
        category="city",
        country="Узбекистан",
        region="Ташкент",
        continent="asia",
        tags=["проспекты"],
        longitude=69.24,
        latitude=41.3,
        radius_km=12,
    ),
    ZoneSpec(
        name="Тбилиси",
        description="Кура в ущелье и старый город",
        difficulty=3,
        category="city",
        country="Грузия",
        region="Тбилиси",
        continent="asia",
        tags=["ущелье"],
        longitude=44.79,
        latitude=41.72,
        radius_km=10,
    ),
    ZoneSpec(
        name="Баку",
        description="Дуга бухты и Пламенные башни",
        difficulty=3,
        category="city",
        country="Азербайджан",
        region="Баку",
        continent="asia",
        tags=["бухта"],
        longitude=49.87,
        latitude=40.41,
        radius_km=12,
    ),
    ZoneSpec(
        name="Ереван",
        description="Радиальный центр и Арарат на горизонте",
        difficulty=3,
        category="city",
        country="Армения",
        region="Ереван",
        continent="asia",
        tags=["кольцо"],
        longitude=44.51,
        latitude=40.18,
        radius_km=10,
    ),
    ZoneSpec(
        name="Ниагарский водопад",
        description="Подкова водопада на границе двух стран",
        difficulty=1,
        category="nature",
        country="Канада",
        region="Онтарио",
        continent="north_america",
        tags=["водопад"],
        longitude=-79.07,
        latitude=43.08,
        radius_km=6,
    ),
    ZoneSpec(
        name="Панамский канал",
        description="Шлюзы Мирафлорес и суда в очереди",
        difficulty=2,
        category="architecture",
        country="Панама",
        region="Панама",
        continent="north_america",
        tags=["канал"],
        longitude=-79.59,
        latitude=8.99,
        radius_km=10,
    ),
    ZoneSpec(
        name="Суэцкий канал",
        description="Прямая линия через пустыню",
        difficulty=2,
        category="architecture",
        country="Египет",
        region="Исмаилия",
        continent="africa",
        tags=["канал"],
        longitude=32.32,
        latitude=30.59,
        radius_km=12,
    ),
    ZoneSpec(
        name="Стоунхендж",
        description="Круг камней среди полей Уилтшира",
        difficulty=3,
        category="historical",
        country="Великобритания",
        region="Англия",
        continent="europe",
        tags=["мегалиты"],
        longitude=-1.83,
        latitude=51.18,
        radius_km=5,
    ),
    ZoneSpec(
        name="Мон-Сен-Мишель",
        description="Остров-аббатство в приливной бухте",
        difficulty=2,
        category="historical",
        country="Франция",
        region="Нормандия",
        continent="europe",
        tags=["аббатство"],
        longitude=-1.51,
        latitude=48.64,
        radius_km=5,
    ),
    ZoneSpec(
        name="Санторини",
        description="Кальдера, залитая морем",
        difficulty=2,
        category="islands",
        country="Греция",
        region="Эгейские острова",
        continent="europe",
        tags=["кальдера"],
        longitude=25.43,
        latitude=36.4,
        radius_km=9,
    ),
    ZoneSpec(
        name="Дубровник",
        description="Крепостные стены на мысу",
        difficulty=2,
        category="historical",
        country="Хорватия",
        region="Далмация",
        continent="europe",
        tags=["крепость"],
        longitude=18.09,
        latitude=42.65,
        radius_km=5,
    ),
    ZoneSpec(
        name="Монако",
        description="Княжество размером с район",
        difficulty=2,
        category="city",
        country="Монако",
        region="Монако",
        continent="europe",
        tags=["порт"],
        longitude=7.42,
        latitude=43.74,
        radius_km=4,
    ),
    ZoneSpec(
        name="Версаль",
        description="Геометрия парка и Большой канал",
        difficulty=1,
        category="architecture",
        country="Франция",
        region="Иль-де-Франс",
        continent="europe",
        tags=["парк"],
        longitude=2.12,
        latitude=48.8,
        radius_km=5,
    ),
]


async def seed(session: AsyncSession, only_new: bool = False) -> tuple[int, int, int]:
    """
    Загрузить зоны в переданную сессию.

    Возвращает количество добавленных, обновлённых и выведенных из игры.
    Сессию открывает вызывающий: так эту функцию можно проверить тестом, не
    трогая настоящую базу.
    """
    added = updated = retired = 0

    existing = {
        zone.name: zone for zone in (await session.execute(select(LocationZone))).scalars().all()
    }

    for spec in ZONES:
        zone = existing.get(spec.name)

        if zone is None:
            zone = LocationZone(name=spec.name, is_active=True)
            session.add(zone)
            added += 1
        elif only_new:
            continue
        else:
            zone.is_active = True
            updated += 1

        _apply(zone, spec)

    if not only_new:
        # Зона, убранная из списка, перестаёт попадаться в новых раундах.
        # Удалять её нельзя: на неё ссылаются уже сыгранные раунды
        wanted = {spec.name for spec in ZONES}
        for name, zone in existing.items():
            if name not in wanted and zone.is_active:
                zone.is_active = False
                retired += 1

    await session.commit()

    return added, updated, retired


async def seed_database(only_new: bool = False) -> tuple[int, int, int]:
    """Загрузить зоны в базу, указанную настройками."""
    async with AsyncSessionLocal() as session:
        return await seed(session, only_new=only_new)


def _apply(zone: LocationZone, spec: ZoneSpec) -> None:
    zone.description = spec.description
    zone.difficulty = spec.difficulty
    zone.category = spec.category
    zone.country = spec.country
    zone.region = spec.region
    zone.continent = spec.continent
    zone.tags = json.dumps(spec.tags, ensure_ascii=False)
    zone.polygon = WKTElement(spec.polygon_wkt(), srid=4326)


def main() -> None:
    parser = argparse.ArgumentParser(description="Загрузка игровых зон Location King")
    parser.add_argument(
        "--only-new",
        action="store_true",
        help="не трогать зоны, которые уже есть в базе",
    )
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(levelname)-8s %(message)s")

    added, updated, retired = asyncio.run(seed_database(only_new=args.only_new))
    logger.info(
        "Зоны загружены: добавлено %s, обновлено %s, выведено из игры %s, всего в списке %s",
        added,
        updated,
        retired,
        len(ZONES),
    )


if __name__ == "__main__":
    main()
