"""
Названия стран на двух языках.

В границах из OpenStreetMap есть только код ISO 3166-1 alpha-3 — названия к
ним нужно приложить. Таблица собрана из CLDR (unicode-org/cldr-json) и
iso-codes и лежит здесь готовой, а не тянется из сети: имена стран меняются
раз в десятилетие, а разбирать их на лету — это ещё одна зависимость и ещё
один повод для развёртывания упасть.

Где короткое имя привычнее полного, взято короткое: «США», а не «Соединённые
Штаты», «UAE», а не «United Arab Emirates». Исключения — там, где короткое
звучит непривычно.

Отсюда же названия берёт загрузчик границ: в базе лежит русское имя, и по
нему каталог зон сходится с границами. Игроку название показывается на его
языке, и решает это уже слой ответов.
"""

from app.messages import Message

COUNTRY_NAMES: dict[str, Message] = {
    "ABW": Message("Аруба", "Aruba"),
    "AFG": Message("Афганистан", "Afghanistan"),
    "AGO": Message("Ангола", "Angola"),
    "AIA": Message("Ангилья", "Anguilla"),
    "ALA": Message("Аландские о-ва", "Åland Islands"),
    "ALB": Message("Албания", "Albania"),
    "AND": Message("Андорра", "Andorra"),
    "ARE": Message("ОАЭ", "UAE"),
    "ARG": Message("Аргентина", "Argentina"),
    "ARM": Message("Армения", "Armenia"),
    "ASM": Message("Американское Самоа", "American Samoa"),
    "ATA": Message("Антарктида", "Antarctica"),
    "ATF": Message("Французские Южные территории", "French Southern Territories"),
    "ATG": Message("Антигуа и Барбуда", "Antigua & Barbuda"),
    "AUS": Message("Австралия", "Australia"),
    "AUT": Message("Австрия", "Austria"),
    "AZE": Message("Азербайджан", "Azerbaijan"),
    "BDI": Message("Бурунди", "Burundi"),
    "BEL": Message("Бельгия", "Belgium"),
    "BEN": Message("Бенин", "Benin"),
    "BES": Message("Бонэйр, Синт-Эстатиус и Саба", "Caribbean Netherlands"),
    "BFA": Message("Буркина-Фасо", "Burkina Faso"),
    "BGD": Message("Бангладеш", "Bangladesh"),
    "BGR": Message("Болгария", "Bulgaria"),
    "BHR": Message("Бахрейн", "Bahrain"),
    "BHS": Message("Багамы", "Bahamas"),
    "BIH": Message("Босния и Герцеговина", "Bosnia & Herzegovina"),
    "BLM": Message("Сен-Бартелеми", "St. Barthélemy"),
    "BLR": Message("Беларусь", "Belarus"),
    "BLZ": Message("Белиз", "Belize"),
    "BMU": Message("Бермудские о-ва", "Bermuda"),
    "BOL": Message("Боливия", "Bolivia"),
    "BRA": Message("Бразилия", "Brazil"),
    "BRB": Message("Барбадос", "Barbados"),
    "BRN": Message("Бруней", "Brunei"),
    "BTN": Message("Бутан", "Bhutan"),
    "BVT": Message("о-в Буве", "Bouvet Island"),
    "BWA": Message("Ботсвана", "Botswana"),
    "CAF": Message("Центрально-Африканская Республика", "Central African Republic"),
    "CAN": Message("Канада", "Canada"),
    "CCK": Message("Кокосовые о-ва", "Cocos (Keeling) Islands"),
    "CHE": Message("Швейцария", "Switzerland"),
    "CHL": Message("Чили", "Chile"),
    "CHN": Message("Китай", "China"),
    "CIV": Message("Кот-д’Ивуар", "Côte d'Ivoire"),
    "CMR": Message("Камерун", "Cameroon"),
    "COD": Message("Конго - Киншаса", "DR Congo"),
    "COG": Message("Конго - Браззавиль", "Congo"),
    "COK": Message("о-ва Кука", "Cook Islands"),
    "COL": Message("Колумбия", "Colombia"),
    "COM": Message("Коморы", "Comoros"),
    "CPV": Message("Кабо-Верде", "Cabo Verde"),
    "CRI": Message("Коста-Рика", "Costa Rica"),
    "CUB": Message("Куба", "Cuba"),
    "CUW": Message("Кюрасао", "Curaçao"),
    "CXR": Message("о-в Рождества", "Christmas Island"),
    "CYM": Message("о-ва Кайман", "Cayman Islands"),
    "CYP": Message("Кипр", "Cyprus"),
    "CZE": Message("Чехия", "Czechia"),
    "DEU": Message("Германия", "Germany"),
    "DJI": Message("Джибути", "Djibouti"),
    "DMA": Message("Доминика", "Dominica"),
    "DNK": Message("Дания", "Denmark"),
    "DOM": Message("Доминиканская Республика", "Dominican Republic"),
    "DZA": Message("Алжир", "Algeria"),
    "ECU": Message("Эквадор", "Ecuador"),
    "EGY": Message("Египет", "Egypt"),
    "ERI": Message("Эритрея", "Eritrea"),
    "ESH": Message("Западная Сахара", "Western Sahara"),
    "ESP": Message("Испания", "Spain"),
    "EST": Message("Эстония", "Estonia"),
    "ETH": Message("Эфиопия", "Ethiopia"),
    "FIN": Message("Финляндия", "Finland"),
    "FJI": Message("Фиджи", "Fiji"),
    "FLK": Message("Фолклендские о-ва", "Falkland Islands"),
    "FRA": Message("Франция", "France"),
    "FRO": Message("Фарерские о-ва", "Faroe Islands"),
    "FSM": Message("Федеративные Штаты Микронезии", "Micronesia"),
    "GAB": Message("Габон", "Gabon"),
    "GBR": Message("Великобритания", "United Kingdom"),
    "GEO": Message("Грузия", "Georgia"),
    "GGY": Message("Гернси", "Guernsey"),
    "GHA": Message("Гана", "Ghana"),
    "GIB": Message("Гибралтар", "Gibraltar"),
    "GIN": Message("Гвинея", "Guinea"),
    "GLP": Message("Гваделупа", "Guadeloupe"),
    "GMB": Message("Гамбия", "Gambia"),
    "GNB": Message("Гвинея-Бисау", "Guinea-Bissau"),
    "GNQ": Message("Экваториальная Гвинея", "Equatorial Guinea"),
    "GRC": Message("Греция", "Greece"),
    "GRD": Message("Гренада", "Grenada"),
    "GRL": Message("Гренландия", "Greenland"),
    "GTM": Message("Гватемала", "Guatemala"),
    "GUF": Message("Французская Гвиана", "French Guiana"),
    "GUM": Message("Гуам", "Guam"),
    "GUY": Message("Гайана", "Guyana"),
    "HKG": Message("Гонконг", "Hong Kong"),
    "HMD": Message("о-ва Херд и Макдональд", "Heard & McDonald Islands"),
    "HND": Message("Гондурас", "Honduras"),
    "HRV": Message("Хорватия", "Croatia"),
    "HTI": Message("Гаити", "Haiti"),
    "HUN": Message("Венгрия", "Hungary"),
    "IDN": Message("Индонезия", "Indonesia"),
    "IMN": Message("о-в Мэн", "Isle of Man"),
    "IND": Message("Индия", "India"),
    "IOT": Message("Британская территория в Индийском океане", "British Indian Ocean Territory"),
    "IRL": Message("Ирландия", "Ireland"),
    "IRN": Message("Иран", "Iran"),
    "IRQ": Message("Ирак", "Iraq"),
    "ISL": Message("Исландия", "Iceland"),
    "ISR": Message("Израиль", "Israel"),
    "ITA": Message("Италия", "Italy"),
    "JAM": Message("Ямайка", "Jamaica"),
    "JEY": Message("Джерси", "Jersey"),
    "JOR": Message("Иордания", "Jordan"),
    "JPN": Message("Япония", "Japan"),
    "KAZ": Message("Казахстан", "Kazakhstan"),
    "KEN": Message("Кения", "Kenya"),
    "KGZ": Message("Киргизия", "Kyrgyzstan"),
    "KHM": Message("Камбоджа", "Cambodia"),
    "KIR": Message("Кирибати", "Kiribati"),
    "KNA": Message("Сент-Китс и Невис", "St. Kitts & Nevis"),
    "KOR": Message("Республика Корея", "South Korea"),
    "KWT": Message("Кувейт", "Kuwait"),
    "LAO": Message("Лаос", "Laos"),
    "LBN": Message("Ливан", "Lebanon"),
    "LBR": Message("Либерия", "Liberia"),
    "LBY": Message("Ливия", "Libya"),
    "LCA": Message("Сент-Люсия", "St. Lucia"),
    "LIE": Message("Лихтенштейн", "Liechtenstein"),
    "LKA": Message("Шри-Ланка", "Sri Lanka"),
    "LSO": Message("Лесото", "Lesotho"),
    "LTU": Message("Литва", "Lithuania"),
    "LUX": Message("Люксембург", "Luxembourg"),
    "LVA": Message("Латвия", "Latvia"),
    "MAC": Message("Макао", "Macao"),
    "MAF": Message("Сен-Мартен", "St. Martin"),
    "MAR": Message("Марокко", "Morocco"),
    "MDA": Message("Молдова", "Moldova"),
    "MDG": Message("Мадагаскар", "Madagascar"),
    "MDV": Message("Мальдивы", "Maldives"),
    "MEX": Message("Мексика", "Mexico"),
    "MHL": Message("Маршалловы о-ва", "Marshall Islands"),
    "MKD": Message("Северная Македония", "North Macedonia"),
    "MLI": Message("Мали", "Mali"),
    "MLT": Message("Мальта", "Malta"),
    "MMR": Message("Мьянма (Бирма)", "Myanmar"),
    "MNE": Message("Черногория", "Montenegro"),
    "MNG": Message("Монголия", "Mongolia"),
    "MNP": Message("Северные Марианские о-ва", "Northern Mariana Islands"),
    "MOZ": Message("Мозамбик", "Mozambique"),
    "MRT": Message("Мавритания", "Mauritania"),
    "MSR": Message("Монтсеррат", "Montserrat"),
    "MTQ": Message("Мартиника", "Martinique"),
    "MUS": Message("Маврикий", "Mauritius"),
    "MWI": Message("Малави", "Malawi"),
    "MYS": Message("Малайзия", "Malaysia"),
    "MYT": Message("Майотта", "Mayotte"),
    "NAM": Message("Намибия", "Namibia"),
    "NCL": Message("Новая Каледония", "New Caledonia"),
    "NER": Message("Нигер", "Niger"),
    "NFK": Message("о-в Норфолк", "Norfolk Island"),
    "NGA": Message("Нигерия", "Nigeria"),
    "NIC": Message("Никарагуа", "Nicaragua"),
    "NIU": Message("Ниуэ", "Niue"),
    "NLD": Message("Нидерланды", "Netherlands"),
    "NOR": Message("Норвегия", "Norway"),
    "NPL": Message("Непал", "Nepal"),
    "NRU": Message("Науру", "Nauru"),
    "NZL": Message("Новая Зеландия", "New Zealand"),
    "OMN": Message("Оман", "Oman"),
    "PAK": Message("Пакистан", "Pakistan"),
    "PAN": Message("Панама", "Panama"),
    "PCN": Message("о-ва Питкэрн", "Pitcairn"),
    "PER": Message("Перу", "Peru"),
    "PHL": Message("Филиппины", "Philippines"),
    "PLW": Message("Палау", "Palau"),
    "PNG": Message("Папуа — Новая Гвинея", "Papua New Guinea"),
    "POL": Message("Польша", "Poland"),
    "PRI": Message("Пуэрто-Рико", "Puerto Rico"),
    "PRK": Message("КНДР", "North Korea"),
    "PRT": Message("Португалия", "Portugal"),
    "PRY": Message("Парагвай", "Paraguay"),
    "PSE": Message("Палестина", "Palestine"),
    "PYF": Message("Французская Полинезия", "French Polynesia"),
    "QAT": Message("Катар", "Qatar"),
    "REU": Message("Реюньон", "Réunion"),
    "ROU": Message("Румыния", "Romania"),
    "RUS": Message("Россия", "Russia"),
    "RWA": Message("Руанда", "Rwanda"),
    "SAU": Message("Саудовская Аравия", "Saudi Arabia"),
    "SDN": Message("Судан", "Sudan"),
    "SEN": Message("Сенегал", "Senegal"),
    "SGP": Message("Сингапур", "Singapore"),
    "SGS": Message("Южная Георгия и Южные Сандвичевы о-ва", "South Georgia"),
    "SHN": Message("о-в Св. Елены", "St. Helena"),
    "SJM": Message("Шпицберген и Ян-Майен", "Svalbard & Jan Mayen"),
    "SLB": Message("Соломоновы о-ва", "Solomon Islands"),
    "SLE": Message("Сьерра-Леоне", "Sierra Leone"),
    "SLV": Message("Сальвадор", "El Salvador"),
    "SMR": Message("Сан-Марино", "San Marino"),
    "SOM": Message("Сомали", "Somalia"),
    "SPM": Message("Сен-Пьер и Микелон", "St. Pierre & Miquelon"),
    "SRB": Message("Сербия", "Serbia"),
    "SSD": Message("Южный Судан", "South Sudan"),
    "STP": Message("Сан-Томе и Принсипи", "São Tomé & Príncipe"),
    "SUR": Message("Суринам", "Suriname"),
    "SVK": Message("Словакия", "Slovakia"),
    "SVN": Message("Словения", "Slovenia"),
    "SWE": Message("Швеция", "Sweden"),
    "SWZ": Message("Эсватини", "Eswatini"),
    "SXM": Message("Синт-Мартен", "Sint Maarten (Dutch part)"),
    "SYC": Message("Сейшельские о-ва", "Seychelles"),
    "SYR": Message("Сирия", "Syria"),
    "TCA": Message("Тёркс и Кайкос", "Turks & Caicos Islands"),
    "TCD": Message("Чад", "Chad"),
    "TGO": Message("Того", "Togo"),
    "THA": Message("Таиланд", "Thailand"),
    "TJK": Message("Таджикистан", "Tajikistan"),
    "TKL": Message("Токелау", "Tokelau"),
    "TKM": Message("Туркменистан", "Turkmenistan"),
    "TLS": Message("Восточный Тимор", "Timor-Leste"),
    "TON": Message("Тонга", "Tonga"),
    "TTO": Message("Тринидад и Тобаго", "Trinidad & Tobago"),
    "TUN": Message("Тунис", "Tunisia"),
    "TUR": Message("Турция", "Türkiye"),
    "TUV": Message("Тувалу", "Tuvalu"),
    "TWN": Message("Тайвань", "Taiwan"),
    "TZA": Message("Танзания", "Tanzania"),
    "UGA": Message("Уганда", "Uganda"),
    "UKR": Message("Украина", "Ukraine"),
    "UMI": Message("Внешние малые о-ва (США)", "U.S. Outlying Islands"),
    "URY": Message("Уругвай", "Uruguay"),
    "USA": Message("США", "United States"),
    "UZB": Message("Узбекистан", "Uzbekistan"),
    "VCT": Message("Сент-Винсент и Гренадины", "St. Vincent & Grenadines"),
    "VEN": Message("Венесуэла", "Venezuela"),
    "VGB": Message("Виргинские о-ва (Великобритания)", "British Virgin Islands"),
    "VIR": Message("Виргинские о-ва (США)", "U.S. Virgin Islands"),
    "VNM": Message("Вьетнам", "Vietnam"),
    "VUT": Message("Вануату", "Vanuatu"),
    "WLF": Message("Уоллис и Футуна", "Wallis & Futuna"),
    "WSM": Message("Самоа", "Samoa"),
    "XKX": Message("Косово", "Kosovo"),
    "YEM": Message("Йемен", "Yemen"),
    "ZAF": Message("Южно-Африканская Республика", "South Africa"),
    "ZMB": Message("Замбия", "Zambia"),
    "ZWE": Message("Зимбабве", "Zimbabwe"),
}


def name_of(code: str | None, language: str) -> str | None:
    """
    Название страны на выбранном языке.

    Кода нет — нет и названия. Код есть, а названия к нему нет — показываем
    сам код: он приехал из границ, и промолчать о стране было бы хуже, чем
    назвать её тремя буквами.
    """
    if code is None:
        return None

    known = COUNTRY_NAMES.get(code)
    return code if known is None else known.text(language)
