"""
Названия мест каталога по-английски.

Каталог написан по-русски: он собирался под русскоязычную игру, и русское имя
остаётся первичным — по нему зона ищется, по нему сходятся границы стран и
подборки. Здесь лежит второе имя для тех же мест: игроку, который выбрал
английский, «Бангкок» кириллицей не говорит ничего.

Отдельной таблицей, а не колонкой в базе: перевод — это свойство текста, а не
данные о месте, и держать его рядом с каталогом дешевле, чем миграцией и
повторной заливкой зон на сервере. Расходиться каталогу и таблице не даёт
тест: он читает `scripts/seed.py` и требует перевод для каждого названия и
каждого региона.

Названия — привычные английские экзонимы: Moscow, а не Moskva, и Cologne, а не
Köln. Где привычного нет, взята латиница, как её пишут на месте.

Описания зон остаются русскими: игроку они не показываются, их читает только
тот, кто правит каталог.
"""

from app.utils.country_names import COUNTRY_NAMES

#: Обратный указатель: каталог знает страну по русскому имени, а таблица —
#: по коду ISO
COUNTRY_NAMES_BY_RUSSIAN = {message.ru: message for message in COUNTRY_NAMES.values()}

PLACE_NAMES: dict[str, str] = {
    "Абу-Даби": "Abu Dhabi",
    "Аддис-Абеба": "Addis Ababa",
    "Аделаида": "Adelaide",
    "Аккра": "Accra",
    "Александрия": "Alexandria",
    "Алжир": "Algiers",
    "Алматы": "Almaty",
    "Алтай": "Altai",
    "Альберта": "Alberta",
    "Амазонас": "Amazonas",
    "Амазонка, средняя": "Middle Amazon",
    "Амман": "Amman",
    "Амстердам": "Amsterdam",
    "Ангкор-Ват": "Angkor Wat",
    "Англия": "England",
    "Андалусия": "Andalusia",
    "Анкара": "Ankara",
    "Антарктида, шельф Росса": "Antarctica, Ross Ice Shelf",
    "Антарктический полуостров": "Antarctic Peninsula",
    "Антверпен": "Antwerp",
    "Антофагаста": "Antofagasta",
    "Антьокия": "Antioquia",
    "Аральское море": "Aral Sea",
    "Аризона": "Arizona",
    "Аруша": "Arusha",
    "Асуан": "Aswan",
    "Асуанская плотина": "Aswan Dam",
    "Атакама": "Atacama",
    "Атланта": "Atlanta",
    "Аттика": "Attica",
    "Аутбэк, Западная Австралия": "Outback, Western Australia",
    "Афины": "Athens",
    "Аэропорт Кансай": "Kansai Airport",
    "Бавария": "Bavaria",
    "Багмати": "Bagmati",
    "Баден-Вюртемберг": "Baden-Württemberg",
    "Баия": "Bahia",
    "Байконур": "Baikonur",
    "Баку": "Baku",
    "Бангалор": "Bangalore",
    "Бангкок": "Bangkok",
    "Барселона": "Barcelona",
    "Башкортостан": "Bashkortostan",
    "Бейрут": "Beirut",
    "Белград": "Belgrade",
    "Берлин": "Berlin",
    "Бильбао": "Bilbao",
    "Богота": "Bogotá",
    "Болонья": "Bologna",
    "Большая Аккра": "Greater Accra",
    "Большой Лондон": "Greater London",
    "Бордо": "Bordeaux",
    "Боробудур": "Borobudur",
    "Бостон": "Boston",
    "Бразилиа": "Brasília",
    "Братислава": "Bratislava",
    "Брисбен": "Brisbane",
    "Британская Колумбия": "British Columbia",
    "Брюссель": "Brussels",
    "Будапешт": "Budapest",
    "Бухарест": "Bucharest",
    "Буэнос-Айрес": "Buenos Aires",
    "Вайоминг": "Wyoming",
    "Вале": "Valais",
    "Валенсия": "Valencia",
    "Ванкувер": "Vancouver",
    "Варшава": "Warsaw",
    "Вашингтон": "Washington",
    "Веллингтон": "Wellington",
    "Вена": "Vienna",
    "Венето": "Veneto",
    "Венеция": "Venice",
    "Версаль": "Versailles",
    "Вестланд": "Vestland",
    "Вестра-Гёталанд": "Västra Götaland",
    "Виктория": "Victoria",
    "Виктория, водопад": "Victoria Falls",
    "Вильнюс": "Vilnius",
    "Виргиния": "Virginia",
    "Владивосток": "Vladivostok",
    "Волгоград": "Volgograd",
    "Волгоградская область": "Volgograd Oblast",
    "Воронеж": "Voronezh",
    "Воронежская область": "Voronezh Oblast",
    "Восточная Гренландия": "East Greenland",
    "Восточная Ява": "East Java",
    "Вроцлав": "Wrocław",
    "Гаага": "The Hague",
    "Гавайи": "Hawaii",
    "Гавайи, Большой остров": "Hawaii, Big Island",
    "Гавана": "Havana",
    "Галапагос": "Galápagos",
    "Галапагосы": "Galápagos Islands",
    "Гамбург": "Hamburg",
    "Гвадалахара": "Guadalajara",
    "Гданьск": "Gdańsk",
    "Генуя": "Genoa",
    "Гессен": "Hesse",
    "Гиза": "Giza",
    "Гималаи, Кхумбу": "Himalayas, Khumbu",
    "Глазго": "Glasgow",
    "Гоби": "Gobi",
    "Гонконг": "Hong Kong",
    "Гранд-Каньон": "Grand Canyon",
    "Гренландия, побережье": "Greenland coast",
    "Гуандун": "Guangdong",
    "Гуанчжоу": "Guangzhou",
    "Гётеборг": "Gothenburg",
    "Дакар": "Dakar",
    "Дакка": "Dhaka",
    "Даллас": "Dallas",
    "Далмация": "Dalmatia",
    "Дар-эс-Салам": "Dar es Salaam",
    "Дели": "Delhi",
    "Дельта": "Delta",
    "Дельта Меконга": "Mekong Delta",
    "Дельта Нила": "Nile Delta",
    "Дельта Окаванго": "Okavango Delta",
    "Денвер": "Denver",
    "Детройт": "Detroit",
    "Джакарта": "Jakarta",
    "Джорджия": "Georgia",
    "Долина Монументов": "Monument Valley",
    "Долина Царей": "Valley of the Kings",
    "Доха": "Doha",
    "Дрезден": "Dresden",
    "Дубай": "Dubai",
    "Дублин": "Dublin",
    "Дубровник": "Dubrovnik",
    "Дунайская дельта": "Danube Delta",
    "Дурбан": "Durban",
    "Екатеринбург": "Yekaterinburg",
    "Ереван": "Yerevan",
    "Женева": "Geneva",
    "Загреб": "Zagreb",
    "Зальцбург": "Salzburg",
    "Западная Австралия": "Western Australia",
    "Западная Бенгалия": "West Bengal",
    "Западная провинция": "Western Province",
    "Западный Кейп": "Western Cape",
    "Земля Виктории": "Victoria Land",
    "Земля Грейама": "Graham Land",
    "Игуасу": "Iguazu",
    "Иерусалим": "Jerusalem",
    "Измир": "İzmir",
    "Ика": "Ica",
    "Иллинойс": "Illinois",
    "Иль-де-Франс": "Île-de-France",
    "Иокогама": "Yokohama",
    "Иркутск": "Irkutsk",
    "Иркутская область": "Irkutsk Oblast",
    "Исландия, юг": "Iceland, south",
    "Исмаилия": "Ismailia",
    "Йеллоустон": "Yellowstone",
    "Казань": "Kazan",
    "Каир": "Cairo",
    "Калгари": "Calgary",
    "Калининград": "Kaliningrad",
    "Калининградская область": "Kaliningrad Oblast",
    "Калифорния": "California",
    "Кампания": "Campania",
    "Камчатка": "Kamchatka",
    "Камчатка, вулканы": "Kamchatka volcanoes",
    "Канадские прерии": "Canadian Prairies",
    "Канзас": "Kansas",
    "Кансай": "Kansai",
    "Канто": "Kanto",
    "Каракалпакстан": "Karakalpakstan",
    "Карачи": "Karachi",
    "Карелия": "Karelia",
    "Карелия, озёра": "Karelia lakes",
    "Карнатака": "Karnataka",
    "Касабланка": "Casablanca",
    "Каспийское побережье": "Caspian coast",
    "Каталония": "Catalonia",
    "Катманду": "Kathmandu",
    "Квазулу-Натал": "KwaZulu-Natal",
    "Квебек": "Quebec",
    "Квинсленд": "Queensland",
    "Кейптаун": "Cape Town",
    "Киев": "Kyiv",
    "Килиманджаро": "Kilimanjaro",
    "Киото": "Kyoto",
    "Кито": "Quito",
    "Колизей": "Colosseum",
    "Колката": "Kolkata",
    "Коломбо": "Colombo",
    "Колорадо": "Colorado",
    "Копенгаген": "Copenhagen",
    "Краков": "Kraków",
    "Краснодар": "Krasnodar",
    "Краснодарский край": "Krasnodar Krai",
    "Красноярск": "Krasnoyarsk",
    "Красноярский край": "Krasnoyarsk Krai",
    "Кратер Нгоронгоро": "Ngorongoro Crater",
    "Крым": "Crimea",
    "Крымское побережье": "Crimean coast",
    "Куала-Лумпур": "Kuala Lumpur",
    "Кундинамарка": "Cundinamarca",
    "Куритиба": "Curitiba",
    "Куршская коса": "Curonian Spit",
    "Куско": "Cusco",
    "Кхумбу": "Khumbu",
    "Кызылординская область": "Kyzylorda Region",
    "Кюсю": "Kyushu",
    "Кёльн": "Cologne",
    "Ла-Пампа": "La Pampa",
    "Ла-Пас": "La Paz",
    "Лагос": "Lagos",
    "Лазурный Берег": "French Riviera",
    "Лас-Вегас": "Las Vegas",
    "Лахор": "Lahore",
    "Лацио": "Lazio",
    "Ленстер": "Leinster",
    "Ливерпуль": "Liverpool",
    "Ливингстон": "Livingstone",
    "Лигурия": "Liguria",
    "Лима": "Lima",
    "Линии Наска": "Nazca Lines",
    "Лион": "Lyon",
    "Лиссабон": "Lisbon",
    "Ломбардия": "Lombardy",
    "Лондон": "London",
    "Лос-Анджелес": "Los Angeles",
    "Луизиана": "Louisiana",
    "Луксор": "Luxor",
    "Лусон": "Luzon",
    "Львов": "Lviv",
    "Львовская область": "Lviv Oblast",
    "Магальянес": "Magallanes",
    "Мадагаскар, запад": "Madagascar, west",
    "Мадрид": "Madrid",
    "Мазовия": "Masovia",
    "Майами": "Miami",
    "Македония": "Macedonia",
    "Малопольша": "Lesser Poland",
    "Мангистау": "Mangystau",
    "Манила": "Manila",
    "Манчестер": "Manchester",
    "Мармара": "Marmara",
    "Марракеш": "Marrakesh",
    "Марсель": "Marseille",
    "Массачусетс": "Massachusetts",
    "Махараштра": "Maharashtra",
    "Мачу-Пикчу": "Machu Picchu",
    "Мачу-Пикчу, цитадель": "Machu Picchu citadel",
    "Медельин": "Medellín",
    "Меконг": "Mekong",
    "Мелаки": "Malacca",
    "Мельбурн": "Melbourne",
    "Метро Манила": "Metro Manila",
    "Мехико": "Mexico City",
    "Милан": "Milan",
    "Минск": "Minsk",
    "Мисьонес": "Misiones",
    "Мичиган": "Michigan",
    "Мон-Сен-Мишель": "Mont-Saint-Michel",
    "Монако": "Monaco",
    "Монреаль": "Montreal",
    "Монтевидео": "Montevideo",
    "Мопти": "Mopti",
    "Москва": "Moscow",
    "Москва, центр": "Moscow, centre",
    "Мумбаи": "Mumbai",
    "Мурманск": "Murmansk",
    "Мурманская область": "Murmansk Oblast",
    "Мюнхен": "Munich",
    "Нагоя": "Nagoya",
    "Найроби": "Nairobi",
    "Намиб, Соссусфлей": "Namib, Sossusvlei",
    "Неаполь": "Naples",
    "Невада": "Nevada",
    "Ниагара-Фолс": "Niagara Falls",
    "Нидерланды, польдеры": "Netherlands polders",
    "Нижегородская область": "Nizhny Novgorod Oblast",
    "Нижний Новгород": "Nizhny Novgorod",
    "Нижняя Силезия": "Lower Silesia",
    "Ницца": "Nice",
    "Новая Аквитания": "Nouvelle-Aquitaine",
    "Новая Зеландия, Южный остров": "New Zealand, South Island",
    "Новосибирск": "Novosibirsk",
    "Новосибирская область": "Novosibirsk Oblast",
    "Новый Орлеан": "New Orleans",
    "Новый Южный Уэльс": "New South Wales",
    "Норвежские фьорды": "Norwegian fjords",
    "Нормандия": "Normandy",
    "Норте": "Norte",
    "Нью-Йорк": "New York",
    "Нью-Йорк, Манхэттен": "New York, Manhattan",
    "Овернь — Рона — Альпы": "Auvergne-Rhône-Alpes",
    "Одесса": "Odesa",
    "Одесская область": "Odesa Oblast",
    "Озеро Байкал": "Lake Baikal",
    "Окленд": "Auckland",
    "Округ Колумбия": "District of Columbia",
    "Окситания": "Occitania",
    "Омск": "Omsk",
    "Омская область": "Omsk Oblast",
    "Онтарио": "Ontario",
    "Орегон": "Oregon",
    "Осака": "Osaka",
    "Осло": "Oslo",
    "Отаго": "Otago",
    "Оттава": "Ottawa",
    "Палермо": "Palermo",
    "Пальма Джумейра": "Palm Jumeirah",
    "Пальманова": "Palmanova",
    "Пампа": "Pampas",
    "Панама": "Panama",
    "Панамский канал": "Panama Canal",
    "Папуа, нагорье": "Papua highlands",
    "Парана": "Paraná",
    "Париж": "Paris",
    "Патагония, Торрес": "Patagonia, Torres",
    "Пекин": "Beijing",
    "Пенджаб": "Punjab",
    "Пенсильвания": "Pennsylvania",
    "Пентагон": "The Pentagon",
    "Пермский край": "Perm Krai",
    "Пермь": "Perm",
    "Перт": "Perth",
    "Пирамиды Гизы": "Pyramids of Giza",
    "Пичинча": "Pichincha",
    "Плотина «Три ущелья»": "Three Gorges Dam",
    "Плотина Гувера": "Hoover Dam",
    "Пномпень": "Phnom Penh",
    "Поморье": "Pomerania",
    "Портленд": "Portland",
    "Порту": "Porto",
    "Потоси": "Potosí",
    "Прага": "Prague",
    "Прибайкалье": "Baikal region",
    "Приморский край": "Primorsky Krai",
    "Прованс": "Provence",
    "Пусан": "Busan",
    "Пустыня Гоби": "Gobi Desert",
    "Пьемонт": "Piedmont",
    "Рига": "Riga",
    "Рим": "Rome",
    "Рио-де-Жанейро": "Rio de Janeiro",
    "Рисовые террасы Ифугао": "Ifugao rice terraces",
    "Ростов-на-Дону": "Rostov-on-Don",
    "Ростовская область": "Rostov Oblast",
    "Роттердам": "Rotterdam",
    "Рурский бассейн": "Ruhr",
    "Саксония": "Saxony",
    "Салар-де-Уюни": "Salar de Uyuni",
    "Салвадор": "Salvador",
    "Салоники": "Thessaloniki",
    "Самара": "Samara",
    "Самарская область": "Samara Oblast",
    "Сан-Диего": "San Diego",
    "Сан-Паулу": "São Paulo",
    "Сан-Франциско": "San Francisco",
    "Санкт-Петербург": "Saint Petersburg",
    "Санторини": "Santorini",
    "Сантьяго": "Santiago",
    "Саппоро": "Sapporo",
    "Саскачеван": "Saskatchewan",
    "Сахара, эрг Убари": "Sahara, Ubari Sand Sea",
    "Сахель": "Sahel",
    "Саяно-Шушенская ГЭС": "Sayano-Shushenskaya Dam",
    "Свердловская область": "Sverdlovsk Oblast",
    "Севастополь": "Sevastopol",
    "Северная Голландия": "North Holland",
    "Северная территория": "Northern Territory",
    "Северный Рейн": "North Rhine",
    "Северный Рейн — Вестфалия": "North Rhine-Westphalia",
    "Северо-Запад": "North West",
    "Севилья": "Seville",
    "Серенгети": "Serengeti",
    "Сеул": "Seoul",
    "Сиань": "Xi'an",
    "Сидней": "Sydney",
    "Сиднейский оперный театр": "Sydney Opera House",
    "Сиемреап": "Siem Reap",
    "Сингапур": "Singapore",
    "Синд": "Sindh",
    "Сицилия": "Sicily",
    "Сиэтл": "Seattle",
    "София": "Sofia",
    "Сочи, побережье": "Sochi coast",
    "Средний Запад, поля": "Midwest fields",
    "Стамбул": "Istanbul",
    "Статуя Свободы": "Statue of Liberty",
    "Стокгольм": "Stockholm",
    "Столичная область": "Capital Region",
    "Стоунхендж": "Stonehenge",
    "Страна Басков": "Basque Country",
    "Сурабая": "Surabaya",
    "Суэцкий канал": "Suez Canal",
    "Сюдюрланд": "Suðurland",
    "Тадж-Махал": "Taj Mahal",
    "Тайбэй": "Taipei",
    "Таллин": "Tallinn",
    "Тамилнад": "Tamil Nadu",
    "Татарстан": "Tatarstan",
    "Ташкент": "Tashkent",
    "Тбилиси": "Tbilisi",
    "Тегеран": "Tehran",
    "Тель-Авив": "Tel Aviv",
    "Теотиуакан": "Teotihuacan",
    "Техас": "Texas",
    "Тибет": "Tibet",
    "Тибетское плато": "Tibetan Plateau",
    "Токио": "Tokyo",
    "Торонто": "Toronto",
    "Тоскана": "Tuscany",
    "Тулуза": "Toulouse",
    "Тулча": "Tulcea",
    "Тунис": "Tunis",
    "Турин": "Turin",
    "Тюбу": "Chūbu",
    "Улуру": "Uluru",
    "Улуру, скала": "Uluru rock",
    "Уттар-Прадеш": "Uttar Pradesh",
    "Уусимаа": "Uusimaa",
    "Уфа": "Ufa",
    "Ухань": "Wuhan",
    "Федеральный округ": "Federal District",
    "Феццан": "Fezzan",
    "Филадельфия": "Philadelphia",
    "Финикс": "Phoenix",
    "Фландрия": "Flanders",
    "Флеволанд": "Flevoland",
    "Флоренция": "Florence",
    "Флорида": "Florida",
    "Флорида-Кис": "Florida Keys",
    "Франкфурт": "Frankfurt",
    "Фриули-Венеция-Джулия": "Friuli Venezia Giulia",
    "Фукуока": "Fukuoka",
    "Хабаровск": "Khabarovsk",
    "Хабаровский край": "Khabarovsk Krai",
    "Хайленд": "Highland",
    "Хайлендс": "Highlands",
    "Хакасия": "Khakassia",
    "Халиско": "Jalisco",
    "Ханой": "Hanoi",
    "Ханчжоу": "Hangzhou",
    "Хардап": "Hardap",
    "Харьков": "Kharkiv",
    "Харьковская область": "Kharkiv Oblast",
    "Харьюмаа": "Harju County",
    "Хельсинки": "Helsinki",
    "Хоккайдо": "Hokkaido",
    "Хошимин": "Ho Chi Minh City",
    "Хубэй": "Hubei",
    "Хьюстон": "Houston",
    "Центральная Ява": "Central Java",
    "Цюрих": "Zurich",
    "Челябинск": "Chelyabinsk",
    "Челябинская область": "Chelyabinsk Oblast",
    "Ченнай": "Chennai",
    "Чжэцзян": "Zhejiang",
    "Чикаго": "Chicago",
    "Чунцин": "Chongqing",
    "Шанхай": "Shanghai",
    "Швейцарские Альпы": "Swiss Alps",
    "Шлюзы Мирафлорес": "Miraflores Locks",
    "Шотландия": "Scotland",
    "Шотландское высокогорье": "Scottish Highlands",
    "Штутгарт": "Stuttgart",
    "Шэньси": "Shaanxi",
    "Шэньчжэнь": "Shenzhen",
    "Эгейские острова": "Aegean Islands",
    "Эдинбург": "Edinburgh",
    "Эйфелева башня": "Eiffel Tower",
    "Эмилия-Романья": "Emilia-Romagna",
    "Эр-Рияд": "Riyadh",
    "Южная Австралия": "South Australia",
    "Южная Голландия": "South Holland",
    "Юкатан": "Yucatán",
    "Юкатан, сеноты": "Yucatán cenotes",
    "Юта": "Utah",
    "Янгон": "Yangon",
}


#: Как страна названа в каталоге против того, как её зовёт таблица стран.
#: Каталог писал человек и называл страны привычно — «ЮАР», а не
#: «Южно-Африканская Республика», — а таблица собрана из CLDR по коду ISO.
#: Монако в границах OSM нет вовсе, поэтому его английское имя живёт только
#: здесь
COUNTRY_ALIASES: dict[str, str] = {
    "ЮАР": "Южно-Африканская Республика",
    "Мьянма": "Мьянма (Бирма)",
    "Южная Корея": "Республика Корея",
}

MISSING_COUNTRIES: dict[str, str] = {
    "Монако": "Monaco",
}


def place_name(value: str | None, language: str) -> str | None:
    """
    Название места на выбранном языке.

    Незнакомое название показываем как есть: каталог правят руками, и место
    без перевода лучше показать по-русски, чем не показать вовсе. Что таких
    мест нет, следит тест.
    """
    if value is None or language != "en":
        return value

    return PLACE_NAMES.get(value, value)


def country_name(value: str | None, language: str) -> str | None:
    """
    Страна зоны на выбранном языке.

    Названия стран уже собраны в `country_names.py` — здесь только перевод с
    того, как страну называет каталог, на то, как её зовёт таблица.
    """
    if value is None or language != "en":
        return value

    known = COUNTRY_NAMES_BY_RUSSIAN.get(COUNTRY_ALIASES.get(value, value))
    if known is not None:
        return known.en

    return MISSING_COUNTRIES.get(value, value)
