"""enhance models with statistics and ratings

Revision ID: 002
Revises: 001
Create Date: 2026-04-14 12:39:00.000000
"""

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # --- USERS table enhancements ---
    op.add_column('users', sa.Column('email', sa.String(255), nullable=True))
    op.add_column('users', sa.Column('display_name', sa.String(100), nullable=True))
    op.add_column('users', sa.Column('games_played', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('games_won', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('total_rounds', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('average_score', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('average_distance', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('best_score', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('worst_score', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('elo_rating', sa.Integer(), server_default='1000', nullable=False))
    op.add_column('users', sa.Column('rank', sa.String(50), nullable=True))
    op.add_column('users', sa.Column('level', sa.Integer(), server_default='1', nullable=False))
    op.add_column('users', sa.Column('experience', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('avatar_url', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(100), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(50), nullable=True))
    op.add_column('users', sa.Column('language', sa.String(10), server_default='ru', nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('is_premium', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True))
    
    # Create indexes for users
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.create_index('ix_users_is_active', 'users', ['is_active'], unique=False)
    
    # --- GAME_SESSIONS table enhancements ---
    op.add_column('game_sessions', sa.Column('time_control', sa.String(20), server_default='unlimited', nullable=False))
    op.add_column('game_sessions', sa.Column('average_score', sa.Integer(), server_default='0', nullable=True))
    op.add_column('game_sessions', sa.Column('best_round_score', sa.Integer(), server_default='0', nullable=False))
    op.add_column('game_sessions', sa.Column('worst_round_score', sa.Integer(), server_default='0', nullable=False))
    op.add_column('game_sessions', sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('game_sessions', sa.Column('title', sa.String(100), nullable=True))
    op.add_column('game_sessions', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('game_sessions', sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('game_sessions', sa.Column('allow_comments', sa.Boolean(), server_default='true', nullable=False))
    
    # Create indexes for game_sessions
    op.create_index('ix_game_sessions_is_public', 'game_sessions', ['is_public'], unique=False)
    
    # --- ROUNDS table enhancements ---
    op.add_column('rounds', sa.Column('status', sa.String(20), server_default='pending', nullable=False))
    op.add_column('rounds', sa.Column('accuracy_percentage', sa.Numeric(5, 2), nullable=True))
    op.add_column('rounds', sa.Column('time_limit_seconds', sa.SmallInteger(), nullable=True))
    op.add_column('rounds', sa.Column('max_score', sa.Integer(), server_default='5000', nullable=False))
    op.add_column('rounds', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rounds', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rounds', sa.Column('satellite_image_url', sa.Text(), nullable=True))
    op.add_column('rounds', sa.Column('hint_used', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('rounds', sa.Column('notes', sa.Text(), nullable=True))
    
    # Update view_extent_km default from 500 to 5
    op.execute("ALTER TABLE rounds ALTER COLUMN view_extent_km SET DEFAULT 5")
    
    # Create indexes for rounds
    op.create_index('ix_rounds_status', 'rounds', ['status'], unique=False)
    
    # --- LOCATION_ZONES table enhancements ---
    op.add_column('location_zones', sa.Column('center_point', geoalchemy2.Geometry(geometry_type='POINT', srid=4326), nullable=True))
    op.add_column('location_zones', sa.Column('area_sq_km', sa.Float(), nullable=True))
    op.add_column('location_zones', sa.Column('total_rounds', sa.Integer(), server_default='0', nullable=False))
    op.add_column('location_zones', sa.Column('average_score', sa.Float(), nullable=True))
    op.add_column('location_zones', sa.Column('average_distance', sa.Float(), nullable=True))
    op.add_column('location_zones', sa.Column('popularity', sa.Integer(), server_default='0', nullable=False))
    op.add_column('location_zones', sa.Column('country', sa.String(100), nullable=True))
    op.add_column('location_zones', sa.Column('region', sa.String(100), nullable=True))
    op.add_column('location_zones', sa.Column('tags', sa.Text(), nullable=True))
    op.add_column('location_zones', sa.Column('thumbnail_url', sa.Text(), nullable=True))
    op.add_column('location_zones', sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('location_zones', sa.Column('is_premium', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('location_zones', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    
    # Update category to have a default value
    op.execute("UPDATE location_zones SET category = 'mixed' WHERE category IS NULL")
    op.alter_column('location_zones', 'category', nullable=False, server_default='mixed')
    
    # Create indexes for location_zones
    op.create_index('ix_location_zones_name', 'location_zones', ['name'], unique=False)
    op.create_index('ix_location_zones_difficulty', 'location_zones', ['difficulty'], unique=False)
    op.create_index('ix_location_zones_category', 'location_zones', ['category'], unique=False)
    op.create_index('ix_location_zones_is_active', 'location_zones', ['is_active'], unique=False)
    op.create_index('ix_location_zones_is_featured', 'location_zones', ['is_featured'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes for location_zones
    op.drop_index('ix_location_zones_is_featured', table_name='location_zones')
    op.drop_index('ix_location_zones_is_active', table_name='location_zones')
    op.drop_index('ix_location_zones_category', table_name='location_zones')
    op.drop_index('ix_location_zones_difficulty', table_name='location_zones')
    op.drop_index('ix_location_zones_name', table_name='location_zones')
    
    # Revert category changes
    op.alter_column('location_zones', 'category', nullable=True, server_default=None)
    op.execute("UPDATE location_zones SET category = NULL WHERE category = 'mixed'")
    
    # Drop columns from location_zones
    op.drop_column('location_zones', 'updated_at')
    op.drop_column('location_zones', 'is_premium')
    op.drop_column('location_zones', 'is_featured')
    op.drop_column('location_zones', 'thumbnail_url')
    op.drop_column('location_zones', 'tags')
    op.drop_column('location_zones', 'region')
    op.drop_column('location_zones', 'country')
    op.drop_column('location_zones', 'popularity')
    op.drop_column('location_zones', 'average_distance')
    op.drop_column('location_zones', 'average_score')
    op.drop_column('location_zones', 'total_rounds')
    op.drop_column('location_zones', 'area_sq_km')
    op.drop_column('location_zones', 'center_point')
    
    # Drop indexes for rounds
    op.drop_index('ix_rounds_status', table_name='rounds')
    
    # Revert view_extent_km default to 500
    op.execute("ALTER TABLE rounds ALTER COLUMN view_extent_km SET DEFAULT 500")
    
    # Drop columns from rounds
    op.drop_column('rounds', 'notes')
    op.drop_column('rounds', 'hint_used')
    op.drop_column('rounds', 'satellite_image_url')
    op.drop_column('rounds', 'completed_at')
    op.drop_column('rounds', 'started_at')
    op.drop_column('rounds', 'max_score')
    op.drop_column('rounds', 'time_limit_seconds')
    op.drop_column('rounds', 'accuracy_percentage')
    op.drop_column('rounds', 'status')
    
    # Drop indexes for game_sessions
    op.drop_index('ix_game_sessions_is_public', table_name='game_sessions')
    
    # Drop columns from game_sessions
    op.drop_column('game_sessions', 'allow_comments')
    op.drop_column('game_sessions', 'is_public')
    op.drop_column('game_sessions', 'description')
    op.drop_column('game_sessions', 'title')
    op.drop_column('game_sessions', 'last_activity_at')
    op.drop_column('game_sessions', 'worst_round_score')
    op.drop_column('game_sessions', 'best_round_score')
    op.drop_column('game_sessions', 'average_score')
    op.drop_column('game_sessions', 'time_control')
    
    # Drop indexes for users
    op.drop_index('ix_users_is_active', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    
    # Drop columns from users
    op.drop_column('users', 'last_activity_at')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'is_premium')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'language')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'country')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'experience')
    op.drop_column('users', 'level')
    op.drop_column('users', 'rank')
    op.drop_column('users', 'elo_rating')
    op.drop_column('users', 'worst_score')
    op.drop_column('users', 'best_score')
    op.drop_column('users', 'average_distance')
    op.drop_column('users', 'average_score')
    op.drop_column('users', 'total_rounds')
    op.drop_column('users', 'games_won')
    op.drop_column('users', 'games_played')
    op.drop_column('users', 'display_name')
    op.drop_column('users', 'email')
    
    # ### end Alembic commands ###